load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "generate",
    srcs = ["main.rs"],
    crate_name = "generate_registration",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/backend-go:portable_backend_go",
        "//crates/backend-rust:portable_backend_rust",
        "//crates/build:portable_build",
        "//crates/check:portable_check",
        "//crates/codegen:portable_codegen",
    ],
)
