//! Closed C17 keyword catalogue; standard-header names are a separate category.

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum CKeyword {
    Alignas,
    Alignof,
    Atomic,
    Bool,
    Complex,
    Generic,
    Imaginary,
    NoReturn,
    StaticAssert,
    ThreadLocal,
    Auto,
    Break,
    Case,
    Char,
    Const,
    Continue,
    Default,
    Do,
    Double,
    Else,
    Enum,
    Extern,
    Float,
    For,
    Goto,
    If,
    Inline,
    Int,
    Long,
    Register,
    Restrict,
    Return,
    Short,
    Signed,
    Sizeof,
    Static,
    Struct,
    Switch,
    Typedef,
    Union,
    Unsigned,
    Void,
    Volatile,
    While,
}

impl CKeyword {
    pub const ALL: [Self; 44] = [
        Self::Alignas,
        Self::Alignof,
        Self::Atomic,
        Self::Bool,
        Self::Complex,
        Self::Generic,
        Self::Imaginary,
        Self::NoReturn,
        Self::StaticAssert,
        Self::ThreadLocal,
        Self::Auto,
        Self::Break,
        Self::Case,
        Self::Char,
        Self::Const,
        Self::Continue,
        Self::Default,
        Self::Do,
        Self::Double,
        Self::Else,
        Self::Enum,
        Self::Extern,
        Self::Float,
        Self::For,
        Self::Goto,
        Self::If,
        Self::Inline,
        Self::Int,
        Self::Long,
        Self::Register,
        Self::Restrict,
        Self::Return,
        Self::Short,
        Self::Signed,
        Self::Sizeof,
        Self::Static,
        Self::Struct,
        Self::Switch,
        Self::Typedef,
        Self::Union,
        Self::Unsigned,
        Self::Void,
        Self::Volatile,
        Self::While,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Alignas => "_Alignas",
            Self::Alignof => "_Alignof",
            Self::Atomic => "_Atomic",
            Self::Bool => "_Bool",
            Self::Complex => "_Complex",
            Self::Generic => "_Generic",
            Self::Imaginary => "_Imaginary",
            Self::NoReturn => "_Noreturn",
            Self::StaticAssert => "_Static_assert",
            Self::ThreadLocal => "_Thread_local",
            Self::Auto => "auto",
            Self::Break => "break",
            Self::Case => "case",
            Self::Char => "char",
            Self::Const => "const",
            Self::Continue => "continue",
            Self::Default => "default",
            Self::Do => "do",
            Self::Double => "double",
            Self::Else => "else",
            Self::Enum => "enum",
            Self::Extern => "extern",
            Self::Float => "float",
            Self::For => "for",
            Self::Goto => "goto",
            Self::If => "if",
            Self::Inline => "inline",
            Self::Int => "int",
            Self::Long => "long",
            Self::Register => "register",
            Self::Restrict => "restrict",
            Self::Return => "return",
            Self::Short => "short",
            Self::Signed => "signed",
            Self::Sizeof => "sizeof",
            Self::Static => "static",
            Self::Struct => "struct",
            Self::Switch => "switch",
            Self::Typedef => "typedef",
            Self::Union => "union",
            Self::Unsigned => "unsigned",
            Self::Void => "void",
            Self::Volatile => "volatile",
            Self::While => "while",
        }
    }

    pub fn from_spelling(value: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|keyword| keyword.as_str() == value)
    }
}
