load("@buildifier_prebuilt//:rules.bzl", "buildifier", "buildifier_test")
load("@rules_rust//rust:defs.bzl", "rust_clippy_test", "rustfmt_test")

rust_clippy_test(
    name = "rust_clippy_test",
    targets = [
        "//crates/backend-go:portable_backend_go",
        "//crates/backend-python:portable_backend_python",
        "//crates/backend-rust:portable_backend_rust",
        "//crates/backend-typescript:portable_backend_typescript",
        "//crates/build:portable_build",
        "//crates/check:portable_check_test",
        "//crates/cli:polyrust",
        "//crates/codegen:portable_codegen",
        "//crates/conformance:portable_conformance",
        "//crates/diagnostics:portable_diagnostics_test",
        "//crates/eval:portable_eval",
        "//crates/ir:portable_ir_test",
        "//examples/registration:generate",
        "//generated-fixtures/rust:generated_rust_test",
        "//smoke/diagnostics:diagnostics_consumer_test",
        "//smoke/rust:rust_smoke_test",
    ],
    transitive = True,
)

rustfmt_test(
    name = "rustfmt_test",
    targets = [
        "//crates/backend-go:portable_backend_go",
        "//crates/backend-python:portable_backend_python",
        "//crates/backend-rust:portable_backend_rust",
        "//crates/backend-typescript:portable_backend_typescript",
        "//crates/build:portable_build",
        "//crates/check:portable_check_test",
        "//crates/cli:polyrust",
        "//crates/codegen:portable_codegen",
        "//crates/conformance:portable_conformance",
        "//crates/diagnostics:portable_diagnostics_test",
        "//crates/eval:portable_eval",
        "//crates/ir:portable_ir_test",
        "//examples/registration:generate",
        "//generated-fixtures/rust:generated_rust_test",
        "//smoke/diagnostics:diagnostics_consumer_test",
        "//smoke/rust:rust_smoke_test",
    ],
    transitive = True,
)

buildifier(
    name = "buildifier_fix",
    exclude_patterns = [
        "./.git/*",
        "./bazel-*/*",
    ],
    lint_mode = "fix",
    mode = "fix",
    tags = ["manual"],
)

buildifier_test(
    name = "buildifier_test",
    exclude_patterns = [
        "./.git/*",
        "./bazel-*/*",
    ],
    lint_mode = "warn",
    mode = "diff",
    no_sandbox = True,
    workspace = "//:MODULE.bazel",
)
