module(
    name = "portable_codegen",
    version = "0.0.0",
)

bazel_dep(name = "buildifier_prebuilt", version = "8.5.1.4")
bazel_dep(name = "rules_go", version = "0.63.0", repo_name = "io_bazel_rules_go")
bazel_dep(name = "rules_rust", version = "0.74.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = ["1.98.0"],
)

go_sdk = use_extension("@io_bazel_rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(
    name = "go_sdk",
    version = "1.25.14",
)
use_repo(go_sdk, "go_sdk")

register_toolchains("@go_sdk//:all")
