//! Typed Python 3.13 generation from checked portable IR v0.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;

use portable_check::v0::{Capability, CheckedProgram};
use portable_codegen::{
    Backend, BackendDescriptor, BackendError, BackendOptions, BackendVersion, CapabilitySupport,
    DeclaredDependency, InjectedHelper, IrVersionRange, OptionsSchema, OutputFile, OutputManifest,
    TargetId,
};
use portable_ir::v0::{Declaration, IrVersion, NodeId, TypeRef};

const RUNTIME: &str = include_str!("runtime.py");

pub struct PythonBackend;

impl Backend for PythonBackend {
    fn descriptor(&self) -> BackendDescriptor {
        BackendDescriptor {
            target: TargetId::parse("org.polyrust.python").expect("valid target"),
            display_name: "Python".into(),
            backend_version: BackendVersion::new(0, 1, 0),
            supported_ir: IrVersionRange::exact(IrVersion::CURRENT),
        }
    }
    fn support(&self, capability: Capability) -> CapabilitySupport {
        match capability {
            Capability::CheckedIntegerArithmetic => CapabilitySupport::Helper {
                helper: "polyrust.runtime.checked-integers.v0".into(),
            },
            Capability::UnicodeScalar => CapabilitySupport::Helper {
                helper: "polyrust.runtime.unicode-scalars.v0".into(),
            },
            Capability::ImmutableList => CapabilitySupport::Helper {
                helper: "polyrust.runtime.immutable-list.v0".into(),
            },
            Capability::Bytes
            | Capability::ContractDispatch
            | Capability::F64
            | Capability::Option
            | Capability::Result
            | Capability::WrappingIntegerArithmetic
            | Capability::BoundedIteration => CapabilitySupport::Native,
        }
    }
    fn options_schema(&self) -> OptionsSchema {
        BTreeMap::new()
    }
    fn generate(
        &self,
        program: &CheckedProgram,
        _options: &BackendOptions,
    ) -> Result<OutputManifest, BackendError> {
        let generator = Generator::new(program);
        let helpers = program
            .capabilities()
            .program()
            .iter()
            .filter_map(|capability| match self.support(*capability) {
                CapabilitySupport::Helper { helper } => Some(InjectedHelper {
                    id: helper,
                    capability: format!("{capability:?}"),
                    files: vec!["src/generated_polyrust/runtime.py".into()],
                }),
                CapabilitySupport::Native | CapabilitySupport::Unsupported { .. } => None,
            })
            .collect();
        OutputManifest::new(
            vec![
                OutputFile::text("pyproject.toml", PYPROJECT),
                OutputFile::text("src/generated_polyrust/__init__.py", generator.module()?),
                OutputFile::text("src/generated_polyrust/runtime.py", RUNTIME),
                OutputFile::text("tests/test_generated.py", generator.tests()),
                OutputFile::text("tests/test_conformance.py", CONFORMANCE),
                OutputFile::text("negative/invalid_option.py", TYPE_NEGATIVE),
            ],
            Vec::<DeclaredDependency>::new(),
            helpers,
        )
        .map_err(BackendError::UnsupportedCapabilities)
    }
}

struct Generator<'a> {
    program: &'a CheckedProgram,
    names: BTreeMap<NodeId, String>,
}

impl<'a> Generator<'a> {
    fn new(program: &'a CheckedProgram) -> Self {
        let names = program
            .module()
            .declarations
            .iter()
            .map(|declaration| {
                (
                    declaration.header().node.id,
                    declaration.header().name.clone(),
                )
            })
            .collect();
        Self { program, names }
    }

    fn module(&self) -> Result<String, BackendError> {
        let document =
            portable_ir::v0::to_canonical_json(self.program.document()).map_err(|error| {
                BackendError::Generation {
                    message: format!("cannot serialize checked IR: {error}"),
                }
            })?;
        let document = String::from_utf8(document).expect("canonical JSON is UTF-8");
        let literal = serde_json::to_string(&document).expect("JSON text string serializes");
        let mut output = String::from(
            "# Generated by PolyRust from checked IR v0.\nfrom __future__ import annotations\n\nimport json\nfrom dataclasses import dataclass, field  # noqa: F401\nfrom typing import Protocol, TypeAlias, cast  # noqa: F401\n\nfrom .runtime import PolyOption, PolyResult, PolyValueResult, Runtime  # noqa: F401\n\n",
        );
        output.push_str(&format!("_runtime = Runtime(json.loads({literal}))\n\n"));
        let mut declarations: Vec<_> = self.program.module().declarations.iter().collect();
        declarations.sort_by_key(|declaration| declaration.header().node.id);
        for declaration in declarations {
            self.declaration(&mut output, declaration);
        }
        let tests: Vec<_> = self.program.module().declarations.iter().filter_map(|declaration| if let Declaration::Test(test) = declaration { Some(serde_json::json!({"invocation": test.invocation, "expected": test.expected})) } else { None }).collect();
        output.push_str(&format!("_TESTS: list[dict[str, object]] = json.loads({})\n\ndef _run_test(index: int) -> tuple[PolyResult[object], object, bool]:\n    test = _TESTS[index]\n    invocation = cast(dict[str, object], test[\"invocation\"])\n    data = cast(dict[str, object], invocation[\"data\"])\n    arguments = tuple(_runtime.decode(cast(dict[str, object], item)) for item in cast(list[object], data[\"arguments\"]))\n    if invocation[\"kind\"] == \"function\":\n        actual = _runtime.invoke(cast(int, data[\"function\"]), arguments)\n    else:\n        actual = _runtime.invoke_method(cast(int, data[\"implementation\"]), cast(int, data[\"method\"]), _runtime.decode(cast(dict[str, object], data[\"receiver\"])), arguments)\n    expected = cast(dict[str, object], test[\"expected\"])\n    return actual, _runtime.decode(cast(dict[str, object], expected[\"data\"])), expected[\"kind\"] == \"error\"\n", serde_json::to_string(&serde_json::to_string(&tests).expect("tests serialize")).expect("test JSON literal")));
        Ok(output)
    }

    fn declaration(&self, output: &mut String, declaration: &Declaration) {
        match declaration {
            Declaration::Alias(item) => output.push_str(&format!("{}: TypeAlias = {}\n\n", type_name(&item.header.name), self.ty(&item.target))),
            Declaration::Record(item) => {
                output.push_str("@dataclass(frozen=True, slots=True)\n");
                output.push_str(&format!("class {}:\n    __poly_decl__: int = field(default={}, init=False, repr=False)\n", type_name(&item.header.name), item.header.node.id.0));
                if item.fields.is_empty() { output.push_str("    pass\n"); } else { for field in &item.fields { output.push_str(&format!("    {}: {}\n", value_name(&field.header.name), self.ty(&field.ty))); } }
                for implementation in self.implementations(item.header.node.id) { for method in &implementation.methods { output.push_str(&format!("\n    def {}(self, {}) -> PolyResult[{}]:\n        return cast(PolyResult[{}], _runtime.invoke_method({}, {}, self, ({})))\n", value_name(&method.header.name), self.parameters(&method.parameters), self.ty(&method.return_type), self.ty(&method.return_type), implementation.header.node.id.0, method.header.node.id.0, tuple_arguments(&method.parameters))); } }
                output.push('\n');
            }
            Declaration::Enum(item) => {
                let mut names = Vec::new();
                for variant in &item.variants { let name = format!("{}{}", type_name(&item.header.name), type_name(&variant.header.name)); names.push(name.clone()); output.push_str("@dataclass(frozen=True, slots=True)\n"); output.push_str(&format!("class {name}:\n    tag: str = field(default={:?}, init=False)\n", variant.header.name)); if variant.fields.is_empty() { output.push_str("    pass\n"); } else { for field in &variant.fields { output.push_str(&format!("    {}: {}\n", value_name(&field.header.name), self.ty(&field.ty))); } } output.push('\n'); }
                output.push_str(&format!("{}: TypeAlias = {}\n\n", type_name(&item.header.name), names.join(" | ")));
            }
            Declaration::Contract(item) => { output.push_str(&format!("class {}(Protocol):\n", type_name(&item.header.name))); if item.methods.is_empty() { output.push_str("    pass\n"); } else { for method in &item.methods { output.push_str(&format!("    def {}(self, {}) -> PolyResult[{}]: ...\n", value_name(&method.header.name), self.parameters(&method.parameters), self.ty(&method.return_type))); } } output.push('\n'); }
            Declaration::Constant(item) => output.push_str(&format!("def {}() -> PolyResult[{}]:\n    return cast(PolyResult[{}], _runtime.read_constant({}))\n\n", value_name(&item.header.name), self.ty(&item.ty), self.ty(&item.ty), item.header.node.id.0)),
            Declaration::Function(item) => output.push_str(&format!("def {}({}) -> PolyResult[{}]:\n    return cast(PolyResult[{}], _runtime.invoke({}, ({})))\n\n", value_name(&item.header.name), self.parameters(&item.parameters), self.ty(&item.return_type), self.ty(&item.return_type), item.header.node.id.0, tuple_arguments(&item.parameters))),
            Declaration::Implementation(_) | Declaration::Test(_) => {}
        }
    }

    fn implementations(&self, record: NodeId) -> Vec<&portable_ir::v0::ImplementationDeclaration> {
        self.program
            .module()
            .declarations
            .iter()
            .filter_map(|declaration| match declaration {
                Declaration::Implementation(item) if item.record == record => Some(item),
                _ => None,
            })
            .collect()
    }
    fn parameters(&self, parameters: &[portable_ir::v0::Parameter]) -> String {
        parameters
            .iter()
            .map(|parameter| {
                format!(
                    "{}: {}",
                    value_name(&parameter.header.name),
                    self.ty(&parameter.ty)
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    }
    fn ty(&self, ty: &TypeRef) -> String {
        match ty {
            TypeRef::Unit => "None".into(),
            TypeRef::Bool => "bool".into(),
            TypeRef::I32 | TypeRef::I64 => "int".into(),
            TypeRef::F64 => "float".into(),
            TypeRef::Char | TypeRef::String => "str".into(),
            TypeRef::Bytes => "bytes".into(),
            TypeRef::List(inner) => format!("tuple[{}, ...]", self.ty(inner)),
            TypeRef::Option(inner) => format!("PolyOption[{}]", self.ty(inner)),
            TypeRef::Result { ok, error } => {
                format!("PolyValueResult[{}, {}]", self.ty(ok), self.ty(error))
            }
            TypeRef::Named(id) | TypeRef::Contract(id) => {
                type_name(self.names.get(id).map(String::as_str).unwrap_or("Unknown"))
            }
        }
    }
    fn tests(&self) -> String {
        let mut output = String::from("from generated_polyrust import _run_test\n\n");
        let mut index = 0;
        for declaration in &self.program.module().declarations {
            if let Declaration::Test(test) = declaration {
                output.push_str(&format!("def test_{}() -> None:\n    actual, expected, expects_error = _run_test({index})\n    assert actual.ok is not expects_error\n    if actual.ok:\n        assert actual.value == expected\n\n", value_name(&test.header.name)));
                index += 1;
            }
        }
        output
    }
}

fn tuple_arguments(parameters: &[portable_ir::v0::Parameter]) -> String {
    match parameters {
        [] => String::new(),
        [one] => format!("{},", value_name(&one.header.name)),
        many => many
            .iter()
            .map(|parameter| value_name(&parameter.header.name))
            .collect::<Vec<_>>()
            .join(", "),
    }
}
fn type_name(name: &str) -> String {
    identifier(name)
}
fn value_name(name: &str) -> String {
    identifier(name)
}
fn identifier(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
        "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
        "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
        "try", "while", "with", "yield", "match", "case",
    ];
    if KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_owned()
    }
}

const PYPROJECT: &str = "[project]\nname = \"generated-polyrust-package\"\nversion = \"0.1.0\"\nrequires-python = \">=3.13\"\ndependencies = []\n\n[tool.pytest.ini_options]\npythonpath = [\"src\"]\ntestpaths = [\"tests\"]\n\n[tool.ruff]\ntarget-version = \"py313\"\nline-length = 120\n\n[tool.ruff.lint]\nselect = [\"E4\", \"E7\", \"E9\", \"F\"]\nignore = [\"E701\", \"E702\"]\n";
const CONFORMANCE: &str = "from generated_polyrust.runtime import checked_i32, checked_i64, scalar_length, wrapping\n\ndef test_twenty_semantic_vectors() -> None:\n    source = (1,)\n    appended = source + (2,)\n    vectors = (\n        checked_i32(0).ok, checked_i32(2**31 - 1).ok, checked_i32(-(2**31)).ok, not checked_i32(2**31).ok, not checked_i32(-(2**31) - 1).ok,\n        checked_i64(0).ok, checked_i64(2**63 - 1).ok, checked_i64(-(2**63)).ok, not checked_i64(2**63).ok, not checked_i64(-(2**63) - 1).ok,\n        wrapping(2**31, 32) == -(2**31), wrapping(-(2**31) - 1, 32) == 2**31 - 1, wrapping(2**63, 64) == -(2**63), wrapping(-(2**63) - 1, 64) == 2**63 - 1,\n        scalar_length(\"a\").ok, scalar_length(\"😀\").value == 1, not scalar_length(\"\\ud800\").ok, len(appended) == 2, id(appended) != id(source), float(\"-0.0\").hex().startswith(\"-\"),\n    )\n    assert len(vectors) == 20\n    assert all(vectors)\n";
const TYPE_NEGATIVE: &str = "from generated_polyrust.runtime import PolyOption\n\ninvalid: PolyOption[int] = PolyOption(tag=1)\n";

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn keyword_and_types() {
        assert_eq!(identifier("class"), "class_");
        assert_eq!(Generator::new(&fixture()).ty(&TypeRef::I64), "int");
    }
    #[test]
    fn deterministic_strict_manifest() {
        let checked = fixture();
        let first = PythonBackend
            .generate(&checked, &BackendOptions::default())
            .unwrap();
        let second = PythonBackend
            .generate(&checked, &BackendOptions::default())
            .unwrap();
        assert_eq!(first.canonical_json(), second.canonical_json());
        assert!(PYPROJECT.contains("py313"));
    }
    #[test]
    fn stable_generated_imports_are_lint_clean_when_declaration_kinds_are_absent() {
        let generated = Generator::new(&fixture()).module().unwrap();
        assert!(generated.contains("from dataclasses import dataclass, field  # noqa: F401"));
    }
    fn fixture() -> CheckedProgram {
        portable_check::v0::check_program(
            portable_ir::v0::from_json(include_bytes!(
                "../../build/testdata/registration.poly.json"
            ))
            .unwrap(),
        )
        .unwrap()
    }
}
