//! Package coherence tests are separate from compiler provenance evidence.
use super::JavaDialect;
use crate::ast::*;
use crate::dialect::JavaInvocationKind;
use portable_codegen::*;
use portable_diagnostics::SourceRef;
use std::{collections::BTreeMap, sync::Arc};

#[path = "source_registration/documentation.rs"]
mod documentation;

fn source() -> SourceRef {
    SourceRef::logical(["java-source-registration"])
}

fn metadata() -> RustSourceOrigin {
    let root = RustDeclarationId {
        crate_id: 7,
        definition_path_hash: 1,
    };
    let module = Arc::new(RustModuleDocumentation {
        declaration: root,
        parent: None,
        location: RustSourceLocation {
            file: "src/lib.rs".into(),
            line: 1,
            column: 1,
        },
        documentation: vec![],
    });
    let ancestry: RustModuleAncestry = vec![module.clone()].into();
    RustSourceOrigin {
        declaration: RustDeclarationId {
            definition_path_hash: 2,
            ..root
        },
        node: RustSourceNode::Declaration,
        module: root,
        location: module.location.clone(),
        visibility: RustVisibility::Public,
        externally_reachable: true,
        documentation: vec![],
        module_ancestors: ancestry.clone(),
        crate_exports: Arc::new(RustCrateExports {
            root,
            modules: BTreeMap::from([(root, BTreeMap::new())]),
            module_ancestries: BTreeMap::from([(root, ancestry)]),
        }),
    }
}

fn fixture(
    module: JavaPackage,
    origin: GeneratedOrigin<JavaDialect>,
) -> TargetAstBuilder<JavaDialect> {
    let mut builder = TargetAstBuilder::new(JavaDialect);
    let id = builder.generated_type(GeneratedType {
        name: "Fixture".into(),
        kind: JavaDeclarationKind::FinalClass,
        visibility: JavaVisibility::Public,
        origin,
        source: source(),
    });
    let file = builder.file(TargetFile::new(
        RelativeOutputPath::new(format!(
            "{}Fixture.java",
            module.source_directory(JavaFilePlacement::Main)
        ))
        .unwrap(),
        SourceRole::PublicApi,
        module,
        JavaFilePlacement::Main,
        vec![JavaFileItem::Type {
            declared: vec![GeneratedSymbolId::Type(id)],
            conformances: JavaConformanceInventory::structural().into(),
            source_package: None,
            dependencies: Default::default(),
            declaration: Box::new(JavaTypeDeclaration {
                declared: Some(id),
                kind: JavaDeclarationKind::FinalClass,
                visibility: JavaVisibility::Public,
                modifiers: vec![],
                name: JavaIdentifier::new("Fixture").unwrap(),
                type_parameters: vec![],
                record_components: vec![],
                heritage: JavaHeritage::None,
                permits: vec![],
                members: vec![],
            }),
        }],
        JavaSourceFileKind::CompilationUnit,
        source(),
    ));
    builder.group(TargetFileGroup::new(
        FileGroupRole::PublicApi,
        vec![TargetFileMember::Source(file)],
        source(),
    ));
    builder
}

fn render(package: TargetAstPackage<JavaDialect>) -> RenderedPackage {
    let verified = verify_unresolved_package(&JavaDialect, package).unwrap();
    let linked = TargetLinker::new(JavaDialect).link_ast(&verified).unwrap();
    let certified = certify_resolved_package(&JavaDialect, linked).unwrap();
    let output = render_certified_package(&crate::render::JavaRenderer, &certified).unwrap();
    for _ in 0..2 {
        assert_eq!(
            output,
            render_certified_package(&crate::render::JavaRenderer, &certified).unwrap()
        );
    }
    output
}

#[test]
fn coherent_source_type_uses_the_existing_certificate_without_changing_syntax() {
    let module = JavaPackage::RustCrate(7);
    let output = render(fixture(module, GeneratedOrigin::RustSource(Arc::new(metadata()))).build());
    let structural = render(
        fixture(
            module,
            GeneratedOrigin::Synthesized(SynthesisReason::TestHarness),
        )
        .build(),
    );
    assert_eq!(output, structural);
    let OutputContents::Text(text) = output.files()[0].contents() else {
        panic!("expected Java");
    };
    assert!(text.starts_with("// Generated by PolyRust.\n"));
    assert!(text.contains("package org.polyrust.generated.r0000000000000007;"));
}

#[test]
fn source_ownership_and_body_local_mutations_reject_through_unresolved_verification() {
    let mut cases = Vec::new();
    for node in [
        RustSourceNode::Parameter(0),
        RustSourceNode::Binding(0),
        RustSourceNode::LexicalScope(0),
    ] {
        let mut origin = metadata();
        origin.node = node;
        cases.push((origin, "declaration origin"));
    }
    let mut origin = metadata();
    origin.declaration.crate_id = 8;
    cases.push((origin, "own RustCrate namespace"));
    let mut origin = metadata();
    origin.module.crate_id = 8;
    cases.push((origin, "must belong to its crate"));
    let mut origin = metadata();
    Arc::make_mut(&mut origin.crate_exports).root.crate_id = 8;
    cases.push((origin, "must belong to its crate"));
    let mut origin = metadata();
    origin.visibility = RustVisibility::RestrictedTo(RustDeclarationId {
        crate_id: 8,
        definition_path_hash: 1,
    });
    cases.push((origin, "must belong to its crate"));
    for (origin, message) in cases {
        let errors = verify_unresolved_package(
            &JavaDialect,
            fixture(
                JavaPackage::RustCrate(7),
                GeneratedOrigin::RustSource(Arc::new(origin)),
            )
            .build(),
        )
        .unwrap_err();
        assert!(
            errors.iter().any(|error| error.message.contains(message)),
            "{errors:?}"
        );
    }
    for module in [JavaPackage::Generated, JavaPackage::RustCrate(8)] {
        let errors = verify_unresolved_package(
            &JavaDialect,
            fixture(module, GeneratedOrigin::RustSource(Arc::new(metadata()))).build(),
        )
        .unwrap_err();
        assert!(
            errors
                .iter()
                .any(|error| error.message.contains("own RustCrate namespace")),
            "{errors:?}"
        );
    }
}

#[derive(Clone, Copy, Debug)]
enum Registration {
    Type,
    Callable,
    Value,
    InterfaceMethod,
}

fn register(
    builder: &mut TargetAstBuilder<JavaDialect>,
    kind: Registration,
    origin: GeneratedOrigin<JavaDialect>,
) {
    let ty = TargetTypeRef::Primitive(JavaPrimitive::Int);
    let signature = TargetCallableSignature {
        invocation: JavaInvocationKind::Static,
        receiver: None,
        parameters: vec![],
        return_type: ty.clone(),
    };
    match kind {
        Registration::Type => {
            builder.generated_type(GeneratedType {
                name: "Extra".into(),
                kind: JavaDeclarationKind::FinalClass,
                visibility: JavaVisibility::Public,
                origin,
                source: source(),
            });
        }
        Registration::Callable => {
            builder.callable(GeneratedCallable {
                name: "Extra".into(),
                signature,
                visibility: JavaVisibility::Public,
                origin,
                source: source(),
            });
        }
        Registration::Value => {
            builder.value(GeneratedValue {
                name: "Extra".into(),
                ty,
                visibility: JavaVisibility::Public,
                origin,
                source: source(),
            });
        }
        Registration::InterfaceMethod => {
            let owner = builder.generated_type(GeneratedType {
                name: "Interface".into(),
                kind: JavaDeclarationKind::Interface,
                visibility: JavaVisibility::Public,
                origin: GeneratedOrigin::Synthesized(SynthesisReason::TestHarness),
                source: source(),
            });
            builder.interface_method(GeneratedInterfaceMethod {
                owner,
                name: "Extra".into(),
                signature,
                origin,
                source: source(),
            });
        }
    }
}

#[test]
fn all_registry_categories_participate_in_source_coherence() {
    // These isolated hook tests deliberately leave added declarations unused:
    // they test the complete registry walk, not successful Java assembly.
    for kind in [
        Registration::Type,
        Registration::Callable,
        Registration::Value,
        Registration::InterfaceMethod,
    ] {
        for duplicate in [false, true] {
            let mut builder = fixture(
                JavaPackage::RustCrate(7),
                GeneratedOrigin::RustSource(Arc::new(metadata())),
            );
            let mut origin = metadata();
            if !duplicate {
                origin.declaration.definition_path_hash = 3;
            }
            register(
                &mut builder,
                kind,
                GeneratedOrigin::RustSource(Arc::new(origin)),
            );
            let errors = JavaDialect.verify_package(&builder.build());
            assert_eq!(errors.is_empty(), !duplicate, "{kind:?}: {errors:?}");
            if duplicate {
                assert!(
                    errors
                        .iter()
                        .any(|error| error.message.contains("multiple Java registrations"))
                );
            }
        }
        let mut builder = fixture(
            JavaPackage::RustCrate(7),
            GeneratedOrigin::Synthesized(SynthesisReason::TestHarness),
        );
        let mut origin = metadata();
        origin.node = RustSourceNode::Binding(4);
        register(
            &mut builder,
            kind,
            GeneratedOrigin::RustSource(Arc::new(origin)),
        );
        let errors = JavaDialect.verify_package(&builder.build());
        assert!(
            errors
                .iter()
                .any(|error| error.message.contains("declaration origin")),
            "{kind:?}: {errors:?}"
        );
    }
}

#[test]
fn source_registration_without_a_source_namespace_rejects() {
    let mut builder = TargetAstBuilder::new(JavaDialect);
    register(
        &mut builder,
        Registration::Type,
        GeneratedOrigin::RustSource(Arc::new(metadata())),
    );
    assert!(
        JavaDialect
            .verify_package(&builder.build())
            .iter()
            .any(|error| error.message.contains("own RustCrate namespace"))
    );
}

#[test]
fn ordinary_java_registration_rules_are_not_bypassed_by_source_metadata() {
    // Same target spelling remains illegal regardless of distinct source IDs.
    let mut builder = fixture(
        JavaPackage::RustCrate(7),
        GeneratedOrigin::RustSource(Arc::new(metadata())),
    );
    let mut origin = metadata();
    origin.declaration.definition_path_hash = 3;
    let duplicate = builder.generated_type(GeneratedType {
        name: "Fixture".into(),
        kind: JavaDeclarationKind::FinalClass,
        visibility: JavaVisibility::Package,
        origin: GeneratedOrigin::RustSource(Arc::new(origin)),
        source: source(),
    });
    let file = builder.file(TargetFile::new(
        RelativeOutputPath::new(
            "src/main/java/org/polyrust/generated/r0000000000000007/Other.java",
        )
        .unwrap(),
        SourceRole::PublicApi,
        JavaPackage::RustCrate(7),
        JavaFilePlacement::Main,
        vec![JavaFileItem::Type {
            declared: vec![GeneratedSymbolId::Type(duplicate)],
            conformances: JavaConformanceInventory::structural().into(),
            source_package: None,
            dependencies: Default::default(),
            declaration: Box::new(JavaTypeDeclaration {
                declared: Some(duplicate),
                kind: JavaDeclarationKind::FinalClass,
                visibility: JavaVisibility::Package,
                modifiers: vec![],
                name: JavaIdentifier::new("Fixture").unwrap(),
                type_parameters: vec![],
                record_components: vec![],
                heritage: JavaHeritage::None,
                permits: vec![],
                members: vec![],
            }),
        }],
        JavaSourceFileKind::CompilationUnit,
        source(),
    ));
    builder.group(TargetFileGroup::new(
        FileGroupRole::PublicApi,
        vec![TargetFileMember::Source(file)],
        source(),
    ));
    assert!(
        JavaDialect
            .verify_package(&builder.clone().build())
            .is_empty()
    );
    let errors = verify_unresolved_package(&JavaDialect, builder.build()).unwrap_err();
    assert!(
        errors
            .iter()
            .any(|error| error.message.contains("top-level type with the same name")),
        "{errors:?}"
    );
}
