load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files([
    "Cargo.toml",
    "src/v0/testdata/every-node.poly.json",
])

rust_library(
    name = "portable_ir",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = glob(["src/v0/testdata/**"]),
    crate_name = "portable_ir",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "portable_ir_test",
    compile_data = glob(["src/v0/testdata/**"]),
    crate = ":portable_ir",
    visibility = ["//visibility:public"],
)
