[package]
name = "polyrust-trim-newlines-example"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
portable_backend_c.workspace = true
portable_backend_cpp.workspace = true
portable_backend_go.workspace = true
portable_backend_java.workspace = true
portable_backend_python.workspace = true
portable_backend_rust.workspace = true
portable_backend_typescript.workspace = true
portable_build.workspace = true
portable_check.workspace = true
portable_codegen.workspace = true
portable_eval.workspace = true

[lints]
workspace = true
