load("@rules_rust//rust:defs.bzl", "rust_test")

rust_test(
    name = "diagnostics_consumer_test",
    srcs = ["consumer_test.rs"],
    crate_name = "diagnostics_consumer_test",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = ["//crates/diagnostics:portable_diagnostics"],
)
