//! Java dialect: member names.

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum JavaMemberName {
    MinValue,
    MaxValue,
    Utf8,
    Report,
    Equals,
    DeepEquals,
    RequireNonNull,
    DoubleToRawLongBits,
    LongBitsToDouble,
    IsNaN,
    Floor,
    Ceil,
    CopyOf,
    Of,
    Length,
    IsEmpty,
    Contains,
    Concat,
    StartsWith,
    EndsWith,
    Substring,
    Replace,
    ValueOf,
    ToUnsignedInt,
    Wrap,
    IsHighSurrogate,
    IsLowSurrogate,
    CharCount,
    CompareTo,
    IntValue,
    LongValue,
    Signum,
    Negate,
    Add,
    Subtract,
    Multiply,
    Divide,
    Remainder,
    ShiftLeft,
    ShiftRight,
    IndexOf,
    CodePointCount,
    OffsetByCodePoints,
    CharAt,
    CodePointAt,
    CodePointBefore,
    GetBytes,
    Size,
    Get,
    SubList,
    AddAll,
    NewDecoder,
    OnMalformedInput,
    OnUnmappableCharacter,
    Decode,
    ToString,
}

impl JavaMemberName {
    pub const fn text(self) -> &'static str {
        match self {
            Self::MinValue => "MIN_VALUE",
            Self::MaxValue => "MAX_VALUE",
            Self::Utf8 => "UTF_8",
            Self::Report => "REPORT",
            Self::Equals => "equals",
            Self::DeepEquals => "deepEquals",
            Self::RequireNonNull => "requireNonNull",
            Self::DoubleToRawLongBits => "doubleToRawLongBits",
            Self::LongBitsToDouble => "longBitsToDouble",
            Self::IsNaN => "isNaN",
            Self::Floor => "floor",
            Self::Ceil => "ceil",
            Self::CopyOf => "copyOf",
            Self::Of => "of",
            Self::Length => "length",
            Self::IsEmpty => "isEmpty",
            Self::Contains => "contains",
            Self::Concat => "concat",
            Self::StartsWith => "startsWith",
            Self::EndsWith => "endsWith",
            Self::Substring => "substring",
            Self::Replace => "replace",
            Self::ValueOf => "valueOf",
            Self::ToUnsignedInt => "toUnsignedInt",
            Self::Wrap => "wrap",
            Self::IsHighSurrogate => "isHighSurrogate",
            Self::IsLowSurrogate => "isLowSurrogate",
            Self::CharCount => "charCount",
            Self::CompareTo => "compareTo",
            Self::IntValue => "intValue",
            Self::LongValue => "longValue",
            Self::Signum => "signum",
            Self::Negate => "negate",
            Self::Add => "add",
            Self::Subtract => "subtract",
            Self::Multiply => "multiply",
            Self::Divide => "divide",
            Self::Remainder => "remainder",
            Self::ShiftLeft => "shiftLeft",
            Self::ShiftRight => "shiftRight",
            Self::IndexOf => "indexOf",
            Self::CodePointCount => "codePointCount",
            Self::OffsetByCodePoints => "offsetByCodePoints",
            Self::CharAt => "charAt",
            Self::CodePointAt => "codePointAt",
            Self::CodePointBefore => "codePointBefore",
            Self::GetBytes => "getBytes",
            Self::Size => "size",
            Self::Get => "get",
            Self::SubList => "subList",
            Self::AddAll => "addAll",
            Self::NewDecoder => "newDecoder",
            Self::OnMalformedInput => "onMalformedInput",
            Self::OnUnmappableCharacter => "onUnmappableCharacter",
            Self::Decode => "decode",
            Self::ToString => "toString",
        }
    }
}
