#!/usr/bin/env bash
set -euo pipefail

runfiles="${RUNFILES_DIR:-$0.runfiles}"
generated="$(find "$runfiles" -path '*/generated/c/src/generated.c' -print -quit)"
if test -z "$generated"; then
  generated="$(find "$runfiles" -path '*/test-generated/src/generated.c' -print -quit)"
fi
test -n "$generated"
package="$(dirname "$(dirname "$generated")")"
mapfile -t sources < <(find -L "$package" -type f \( -name '*.c' -o -name '*.h' \) -print | sort)
test "${#sources[@]}" -ge 6
if grep -n $'\t\|\r\|[[:blank:]]$' "${sources[@]}"; then
  echo "C style gate found tabs, carriage returns, or trailing whitespace" >&2
  exit 1
fi
grep -q '^#ifndef .*_GENERATED_H$' "$package/src/generated.h"
grep -q '^#ifndef POLYRUST_RUNTIME_H$' "$package/src/runtime.h"
grep -q 'Generated by PolyRust from checked IR v0' "$package/src/generated.c"
