use portable_codegen::{
    CertifiedTemplateEngine, CertifiedTemplateId, EmbeddedTemplate, GeneratedSymbolId, LinkedFile,
    LinkedTargetPackage, ResolvedTemplateRenderer, TargetSymbolRef,
};
use portable_diagnostics::{Diagnostic, DiagnosticCode};
use serde::Serialize;

use crate::{ast::*, dialect::*};

#[derive(Clone, Copy, Debug, Default)]
pub struct JavaRenderer;

impl CertifiedTemplateId for JavaTemplateId {
    fn all() -> &'static [Self] {
        &Self::ALL
    }
}

#[derive(Serialize)]
pub struct JavaFileView {
    banner: String,
    package: String,
    imports: String,
    declarations: String,
}

impl ResolvedTemplateRenderer<JavaDialect> for JavaRenderer {
    type FileView = JavaFileView;

    fn target_name(&self) -> &'static str {
        "org.polyrust.java"
    }

    fn templates(&self) -> Vec<EmbeddedTemplate<JavaTemplateId>> {
        java_templates()
    }

    fn build_file_view(
        &self,
        _package: &LinkedTargetPackage<JavaDialect>,
        file: &LinkedFile<JavaDialect>,
        templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    ) -> Result<Self::FileView, Vec<Diagnostic>> {
        let banner = render_template(
            templates,
            JavaTemplateId::Comment,
            &CommentView {
                comment: "Generated by PolyRust from verified CoreIR.",
            },
            file,
        )?;
        let package = render_template(
            templates,
            JavaTemplateId::Package,
            &PackageView {
                name: file.module().name(),
            },
            file,
        )?;
        let mut imports = String::new();
        for import in file.imports() {
            imports.push_str(&render_template(
                templates,
                JavaTemplateId::Import,
                &ImportView {
                    path: import.kind().qualified_name(),
                },
                file,
            )?);
        }
        if !imports.is_empty() {
            imports.push('\n');
        }

        let declarations = if *file.placement() == JavaFilePlacement::Runtime {
            render_runtime_file(file, templates)?
        } else {
            let mut output = String::new();
            for item in file.items() {
                match &item.item {
                    JavaFileItem::Type { declaration, .. } => {
                        output.push_str(&render_type(
                            declaration,
                            &item.names,
                            0,
                            templates,
                            file,
                        )?);
                    }
                    JavaFileItem::RuntimeMembers { .. } => {
                        return Err(vec![render_diagnostic(
                            file,
                            "runtime member fragment appeared outside the runtime file",
                        )]);
                    }
                }
            }
            output
        };
        Ok(JavaFileView {
            banner,
            package,
            imports,
            declarations,
        })
    }
}

fn java_templates() -> Vec<EmbeddedTemplate<JavaTemplateId>> {
    use JavaTemplateId as Id;
    vec![
        template(
            Id::CompilationUnit,
            "{{banner}}{{package}}{{imports}}{{declarations}}",
            &["banner", "package", "imports", "declarations"],
        ),
        template(Id::Package, "package {{name}};\n\n", &["name"]),
        template(Id::Import, "import {{path}};\n", &["path"]),
        template(Id::Annotation, "{{indent}}@{{name}}\n", &["indent", "name"]),
        template(Id::Heritage, "{{clause}}", &["clause"]),
        template(
            Id::Class,
            "{{indent}}{{visibility}}{{modifiers}}final class {{name}}{{type_parameters}}{{heritage}} {\n{{members}}{{indent}}}\n",
            &[
                "indent",
                "visibility",
                "modifiers",
                "name",
                "type_parameters",
                "heritage",
                "members",
            ],
        ),
        template(
            Id::Record,
            "{{indent}}{{visibility}}{{modifiers}}record {{name}}{{type_parameters}}({{components}}){{heritage}} {\n{{members}}{{indent}}}\n",
            &[
                "indent",
                "visibility",
                "modifiers",
                "name",
                "type_parameters",
                "components",
                "heritage",
                "members",
            ],
        ),
        template(
            Id::Interface,
            "{{indent}}{{visibility}}{{modifiers}}interface {{name}}{{type_parameters}} {\n{{members}}{{indent}}}\n",
            &[
                "indent",
                "visibility",
                "modifiers",
                "name",
                "type_parameters",
                "members",
            ],
        ),
        template(
            Id::SealedInterface,
            "{{indent}}{{visibility}}{{modifiers}}sealed interface {{name}}{{type_parameters}} permits {{permits}} {\n{{members}}{{indent}}}\n",
            &[
                "indent",
                "visibility",
                "modifiers",
                "name",
                "type_parameters",
                "permits",
                "members",
            ],
        ),
        template(
            Id::Field,
            "{{indent}}{{modifiers}}{{ty}} {{name}}{{initializer}};\n",
            &["indent", "modifiers", "ty", "name", "initializer"],
        ),
        template(
            Id::Method,
            "{{annotations}}{{indent}}{{modifiers}}{{type_parameters}}{{return_type}} {{name}}({{parameters}}) {\n{{body}}{{indent}}}\n",
            &[
                "annotations",
                "indent",
                "modifiers",
                "type_parameters",
                "return_type",
                "name",
                "parameters",
                "body",
            ],
        ),
        template(
            Id::AbstractMethod,
            "{{annotations}}{{indent}}{{modifiers}}{{type_parameters}}{{return_type}} {{name}}({{parameters}});\n",
            &[
                "annotations",
                "indent",
                "modifiers",
                "type_parameters",
                "return_type",
                "name",
                "parameters",
            ],
        ),
        template(
            Id::Constructor,
            "{{indent}}{{modifiers}}{{name}}({{parameters}}) {\n{{body}}{{indent}}}\n",
            &["indent", "modifiers", "name", "parameters", "body"],
        ),
        template(
            Id::Parameter,
            "{{finality}}{{ty}} {{name}}",
            &["finality", "ty", "name"],
        ),
        template(Id::Block, "{{statements}}", &["statements"]),
        template(
            Id::Local,
            "{{indent}}{{finality}}{{ty}} {{name}}{{initializer}};\n",
            &["indent", "finality", "ty", "name", "initializer"],
        ),
        template(
            Id::Assign,
            "{{indent}}{{target}} = {{value}};\n",
            &["indent", "target", "value"],
        ),
        template(
            Id::ExpressionStatement,
            "{{indent}}{{value}};\n",
            &["indent", "value"],
        ),
        template(
            Id::Return,
            "{{indent}}return{{value}};\n",
            &["indent", "value"],
        ),
        template(
            Id::If,
            "{{indent}}if ({{condition}}) {\n{{then_body}}{{indent}} }{{alternate_body}}\n",
            &["indent", "condition", "then_body", "alternate_body"],
        ),
        template(
            Id::ForEach,
            "{{indent}}for ({{ty}} {{binding}} : {{iterable}}) {\n{{body}}{{indent}}}\n",
            &["indent", "ty", "binding", "iterable", "body"],
        ),
        template(
            Id::While,
            "{{indent}}while ({{condition}}) {\n{{body}}{{indent}}}\n",
            &["indent", "condition", "body"],
        ),
        template(
            Id::Switch,
            "{{indent}}switch ({{value}}) {\n{{arms}}{{indent}}}\n",
            &["indent", "value", "arms"],
        ),
        template(
            Id::SwitchArm,
            "{{indent}}{{pattern}} -> {\n{{body}}{{indent}}}\n",
            &["indent", "pattern", "body"],
        ),
        template(
            Id::TryCatch,
            "{{indent}}try {\n{{body}}{{indent}} }{{catches}}\n",
            &["indent", "body", "catches"],
        ),
        template(
            Id::Catch,
            " catch ({{exception_type}} {{binding}}) {\n{{body}}{{indent}} }",
            &["exception_type", "binding", "body", "indent"],
        ),
        template(
            Id::Throw,
            "{{indent}}throw new AssertionError({{message}});\n",
            &["indent", "message"],
        ),
        template(
            Id::ThrowValue,
            "{{indent}}throw {{value}};\n",
            &["indent", "value"],
        ),
        template(Id::Break, "{{indent}}break;\n", &["indent"]),
        template(Id::Continue, "{{indent}}continue;\n", &["indent"]),
        template(Id::Literal, "{{value}}", &["value"]),
        template(Id::Name, "{{value}}", &["value"]),
        template(
            Id::Unary,
            "({{operator}}{{operand}})",
            &["operator", "operand"],
        ),
        template(
            Id::Binary,
            "({{left}} {{operator}} {{right}})",
            &["left", "operator", "right"],
        ),
        template(
            Id::Conditional,
            "({{condition}} ? {{when_true}} : {{when_false}})",
            &["condition", "when_true", "when_false"],
        ),
        template(
            Id::Call,
            "{{target}}({{arguments}})",
            &["target", "arguments"],
        ),
        template(
            Id::New,
            "new {{target}}({{arguments}})",
            &["target", "arguments"],
        ),
        template(
            Id::FieldAccess,
            "{{receiver}}.{{field}}",
            &["receiver", "field"],
        ),
        template(Id::Cast, "(({{target}}) {{value}})", &["target", "value"]),
        template(
            Id::InstanceOf,
            "({{value}} instanceof {{target}}{{binding}})",
            &["value", "target", "binding"],
        ),
        template(
            Id::NewArray,
            "new {{component}}[{{length}}]",
            &["component", "length"],
        ),
        template(Id::ArrayIndex, "{{array}}[{{index}}]", &["array", "index"]),
        template(
            Id::Lambda,
            "({{parameters}}) -> {\n{{body}}{{indent}} }",
            &["parameters", "body", "indent"],
        ),
        template(Id::Comment, "// {{comment}}\n", &["comment"]),
    ]
}

fn template(
    id: JavaTemplateId,
    source: &'static str,
    fields: &'static [&'static str],
) -> EmbeddedTemplate<JavaTemplateId> {
    EmbeddedTemplate::new(id, source, fields)
}

fn render_template<V: Serialize>(
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    id: JavaTemplateId,
    view: &V,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    templates.render(&id, view, "org.polyrust.java", file)
}

fn render_runtime_file(
    file: &LinkedFile<JavaDialect>,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
) -> Result<String, Vec<Diagnostic>> {
    let mut shell = None;
    let mut extra = String::new();
    for item in file.items() {
        match &item.item {
            JavaFileItem::Type { declaration, .. } => {
                if shell.replace((declaration, &item.names)).is_some() {
                    return Err(vec![render_diagnostic(
                        file,
                        "runtime file has multiple class shells",
                    )]);
                }
            }
            JavaFileItem::RuntimeMembers { members, .. } => {
                for member in members {
                    extra.push_str(&render_member(member, &item.names, 1, templates, file)?);
                }
            }
        }
    }
    let Some((shell, names)) = shell else {
        return Err(vec![render_diagnostic(
            file,
            "runtime file has no typed class shell",
        )]);
    };
    render_type_with_extra(shell, names, 0, &extra, templates, file)
}

fn render_diagnostic(file: &LinkedFile<JavaDialect>, message: &str) -> Diagnostic {
    Diagnostic::error(
        DiagnosticCode::InvalidStructure,
        message,
        file.source().clone(),
    )
}

#[derive(Serialize)]
struct CommentView<'a> {
    comment: &'a str,
}
#[derive(Serialize)]
struct PackageView<'a> {
    name: &'a str,
}
#[derive(Serialize)]
struct ImportView<'a> {
    path: &'a str,
}

fn render_type(
    value: &JavaTypeDeclaration,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    render_type_with_extra(value, names, depth, "", templates, file)
}

fn render_type_with_extra(
    value: &JavaTypeDeclaration,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    extra_members: &str,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indent = indent(depth);
    let visibility = visibility(value.visibility, true);
    let declaration_modifiers = modifiers(&value.modifiers);
    let type_parameters = render_type_parameters(&value.type_parameters);
    let declaration_name = match value.declared {
        Some(symbol) => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::Type(symbol)),
        )?,
        None => value.name.as_str().to_owned(),
    };
    let heritage = render_heritage(&value.heritage, names)?;
    let mut members = String::new();
    for member in &value.members {
        members.push_str(&render_member(member, names, depth + 1, templates, file)?);
    }
    members.push_str(extra_members);
    let components = value
        .record_components
        .iter()
        .map(|component| {
            Ok(format!(
                "{} {}",
                render_java_type(&component.ty, names)?,
                component.name.as_str()
            ))
        })
        .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
        .join(", ");
    let permits = value
        .permits
        .iter()
        .map(|ty| render_java_type(ty, names))
        .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
        .join(", ");
    match value.kind {
        JavaDeclarationKind::FinalClass => render_template(
            templates,
            JavaTemplateId::Class,
            &ClassView {
                indent: &indent,
                visibility,
                modifiers: &declaration_modifiers,
                name: &declaration_name,
                type_parameters: &type_parameters,
                heritage: &heritage,
                members: &members,
            },
            file,
        ),
        JavaDeclarationKind::Record => render_template(
            templates,
            JavaTemplateId::Record,
            &RecordView {
                indent: &indent,
                visibility,
                modifiers: &declaration_modifiers,
                name: &declaration_name,
                type_parameters: &type_parameters,
                components: &components,
                heritage: &heritage,
                members: &members,
            },
            file,
        ),
        JavaDeclarationKind::Interface => render_template(
            templates,
            JavaTemplateId::Interface,
            &InterfaceView {
                indent: &indent,
                visibility,
                modifiers: &declaration_modifiers,
                name: &declaration_name,
                type_parameters: &type_parameters,
                members: &members,
            },
            file,
        ),
        JavaDeclarationKind::SealedInterface => render_template(
            templates,
            JavaTemplateId::SealedInterface,
            &SealedInterfaceView {
                indent: &indent,
                visibility,
                modifiers: &declaration_modifiers,
                name: &declaration_name,
                type_parameters: &type_parameters,
                permits: &permits,
                members: &members,
            },
            file,
        ),
    }
}

fn render_member(
    value: &JavaMember,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    match value {
        JavaMember::Field(value) => render_field(value, names, depth, templates, file),
        JavaMember::CompileFailField(value) => {
            let field = JavaField {
                declared: None,
                modifiers: value.modifiers.clone(),
                ty: value.expected_type.clone(),
                name: value.name.clone(),
                initializer: Some(value.initializer.clone()),
            };
            render_field(&field, names, depth, templates, file)
        }
        JavaMember::Method(value) => render_method(value, names, depth, templates, file),
        JavaMember::Constructor(value) => render_constructor(value, names, depth, templates, file),
        JavaMember::NestedType(value) => render_type(value, names, depth, templates, file),
    }
}

fn render_field(
    value: &JavaField,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indent = indent(depth);
    let modifiers = modifiers(&value.modifiers);
    let ty = render_java_type(&value.ty, names)?;
    let initializer = match &value.initializer {
        Some(value) => format!(" = {}", render_expr(value, names, templates, file)?),
        None => String::new(),
    };
    let field_name = match value.declared {
        Some(symbol) => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::Value(symbol)),
        )?,
        None => value.name.as_str().to_owned(),
    };
    render_template(
        templates,
        JavaTemplateId::Field,
        &FieldView {
            indent: &indent,
            modifiers: &modifiers,
            ty: &ty,
            name: &field_name,
            initializer: &initializer,
        },
        file,
    )
}

fn render_method(
    value: &JavaMethod,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indent = indent(depth);
    let annotations = render_annotations(&value.annotations, depth, templates, file)?;
    let modifiers = modifiers(&value.modifiers);
    let type_parameters = render_method_type_parameters(&value.type_parameters);
    let return_type = render_java_type(&value.return_type, names)?;
    let parameters = render_parameters(&value.parameters, names, templates, file)?;
    let method_name = match value.declared {
        JavaMethodDeclaration::Callable(symbol) => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::Callable(symbol)),
        )?,
        JavaMethodDeclaration::Interface(symbol)
        | JavaMethodDeclaration::Implementation {
            interface: symbol, ..
        } => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::InterfaceMethod(symbol)),
        )?,
        JavaMethodDeclaration::Structural => value.name.as_str().to_owned(),
    };
    match &value.body {
        Some(body) => {
            let body = render_block(body, names, depth + 1, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::Method,
                &MethodView {
                    annotations: &annotations,
                    indent: &indent,
                    modifiers: &modifiers,
                    type_parameters: &type_parameters,
                    return_type: &return_type,
                    name: &method_name,
                    parameters: &parameters,
                    body: &body,
                },
                file,
            )
        }
        None => render_template(
            templates,
            JavaTemplateId::AbstractMethod,
            &AbstractMethodView {
                annotations: &annotations,
                indent: &indent,
                modifiers: &modifiers,
                type_parameters: &type_parameters,
                return_type: &return_type,
                name: &method_name,
                parameters: &parameters,
            },
            file,
        ),
    }
}

fn render_constructor(
    value: &JavaConstructor,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indent = indent(depth);
    let modifiers = modifiers(&value.modifiers);
    let parameters = render_parameters(&value.parameters, names, templates, file)?;
    let body = render_block(&value.body, names, depth + 1, templates, file)?;
    render_template(
        templates,
        JavaTemplateId::Constructor,
        &ConstructorView {
            indent: &indent,
            modifiers: &modifiers,
            name: value.name.as_str(),
            parameters: &parameters,
            body: &body,
        },
        file,
    )
}

fn render_annotations(
    values: &[JavaAnnotation],
    depth: usize,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let mut output = String::new();
    let indent = indent(depth);
    for value in values {
        let name = match value {
            JavaAnnotation::Override => "Override",
            JavaAnnotation::SafeVarargs => "SafeVarargs",
        };
        output.push_str(&render_template(
            templates,
            JavaTemplateId::Annotation,
            &AnnotationView {
                indent: &indent,
                name,
            },
            file,
        )?);
    }
    Ok(output)
}

fn render_parameters(
    values: &[JavaParameter],
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    values
        .iter()
        .map(|value| {
            let ty = render_java_type(&value.ty, names)?;
            render_template(
                templates,
                JavaTemplateId::Parameter,
                &ParameterView {
                    finality: if value.final_parameter { "final " } else { "" },
                    ty: &ty,
                    name: value.name.as_str(),
                },
                file,
            )
        })
        .collect::<Result<Vec<_>, Vec<Diagnostic>>>()
        .map(|values| values.join(", "))
}

#[derive(Serialize)]
struct ClassView<'a> {
    indent: &'a str,
    visibility: &'a str,
    modifiers: &'a str,
    name: &'a str,
    type_parameters: &'a str,
    heritage: &'a str,
    members: &'a str,
}
#[derive(Serialize)]
struct RecordView<'a> {
    indent: &'a str,
    visibility: &'a str,
    modifiers: &'a str,
    name: &'a str,
    type_parameters: &'a str,
    components: &'a str,
    heritage: &'a str,
    members: &'a str,
}
#[derive(Serialize)]
struct InterfaceView<'a> {
    indent: &'a str,
    visibility: &'a str,
    modifiers: &'a str,
    name: &'a str,
    type_parameters: &'a str,
    members: &'a str,
}
#[derive(Serialize)]
struct SealedInterfaceView<'a> {
    indent: &'a str,
    visibility: &'a str,
    modifiers: &'a str,
    name: &'a str,
    type_parameters: &'a str,
    permits: &'a str,
    members: &'a str,
}
#[derive(Serialize)]
struct FieldView<'a> {
    indent: &'a str,
    modifiers: &'a str,
    ty: &'a str,
    name: &'a str,
    initializer: &'a str,
}
#[derive(Serialize)]
struct MethodView<'a> {
    annotations: &'a str,
    indent: &'a str,
    modifiers: &'a str,
    type_parameters: &'a str,
    return_type: &'a str,
    name: &'a str,
    parameters: &'a str,
    body: &'a str,
}
#[derive(Serialize)]
struct AbstractMethodView<'a> {
    annotations: &'a str,
    indent: &'a str,
    modifiers: &'a str,
    type_parameters: &'a str,
    return_type: &'a str,
    name: &'a str,
    parameters: &'a str,
}
#[derive(Serialize)]
struct ConstructorView<'a> {
    indent: &'a str,
    modifiers: &'a str,
    name: &'a str,
    parameters: &'a str,
    body: &'a str,
}
#[derive(Serialize)]
struct AnnotationView<'a> {
    indent: &'a str,
    name: &'a str,
}
#[derive(Serialize)]
struct ParameterView<'a> {
    finality: &'a str,
    ty: &'a str,
    name: &'a str,
}

fn render_block(
    value: &JavaBlock,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let mut statements = String::new();
    for statement in &value.statements {
        statements.push_str(&render_stmt(statement, names, depth, templates, file)?);
    }
    render_template(
        templates,
        JavaTemplateId::Block,
        &BlockView {
            statements: &statements,
        },
        file,
    )
}

fn render_stmt(
    value: &JavaStmt,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indentation = indent(depth);
    match value {
        JavaStmt::Local {
            finality,
            ty,
            name,
            value,
        } => {
            let ty = render_java_type(ty, names)?;
            let initializer = match value {
                Some(value) => format!(" = {}", render_expr(value, names, templates, file)?),
                None => String::new(),
            };
            render_template(
                templates,
                JavaTemplateId::Local,
                &LocalView {
                    indent: &indentation,
                    finality: if *finality == JavaLocalFinality::Final {
                        "final "
                    } else {
                        ""
                    },
                    ty: &ty,
                    name: name.as_str(),
                    initializer: &initializer,
                },
                file,
            )
        }
        JavaStmt::Assign { target, value } => {
            let target = render_expr(target, names, templates, file)?;
            let value = render_expr(value, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::Assign,
                &AssignView {
                    indent: &indentation,
                    target: &target,
                    value: &value,
                },
                file,
            )
        }
        JavaStmt::Expression(value) => {
            let value = render_expr(value, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::ExpressionStatement,
                &ExpressionStatementView {
                    indent: &indentation,
                    value: &value,
                },
                file,
            )
        }
        JavaStmt::Return(value) => {
            let value = match value {
                Some(value) => format!(" {}", render_expr(value, names, templates, file)?),
                None => String::new(),
            };
            render_template(
                templates,
                JavaTemplateId::Return,
                &ReturnView {
                    indent: &indentation,
                    value: &value,
                },
                file,
            )
        }
        JavaStmt::If {
            condition,
            then_block,
            else_block,
        } => {
            let condition = render_expr(condition, names, templates, file)?;
            let then_body = render_block(then_block, names, depth + 1, templates, file)?;
            let else_body = match else_block {
                Some(value) => format!(
                    " else {{\n{}{}}}",
                    render_block(value, names, depth + 1, templates, file)?,
                    indentation
                ),
                None => String::new(),
            };
            render_template(
                templates,
                JavaTemplateId::If,
                &IfView {
                    indent: &indentation,
                    condition: &condition,
                    then_body: &then_body,
                    alternate_body: &else_body,
                },
                file,
            )
        }
        JavaStmt::ForEach {
            binding_type,
            binding,
            iterable,
            body,
        } => {
            let ty = render_java_type(binding_type, names)?;
            let iterable = render_expr(iterable, names, templates, file)?;
            let body = render_block(body, names, depth + 1, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::ForEach,
                &ForEachView {
                    indent: &indentation,
                    ty: &ty,
                    binding: binding.as_str(),
                    iterable: &iterable,
                    body: &body,
                },
                file,
            )
        }
        JavaStmt::While { condition, body } => {
            let condition = render_expr(condition, names, templates, file)?;
            let body = render_block(body, names, depth + 1, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::While,
                &WhileView {
                    indent: &indentation,
                    condition: &condition,
                    body: &body,
                },
                file,
            )
        }
        JavaStmt::Switch { value, arms } => {
            let value = render_expr(value, names, templates, file)?;
            let mut rendered_arms = String::new();
            for arm in arms {
                let pattern = match &arm.pattern {
                    JavaPattern::Default => "default".to_owned(),
                    JavaPattern::Literal(value) => render_literal(value),
                    JavaPattern::Type { ty, binding } => {
                        format!("case {} {}", render_java_type(ty, names)?, binding.as_str())
                    }
                };
                let body = render_block(&arm.body, names, depth + 2, templates, file)?;
                rendered_arms.push_str(&render_template(
                    templates,
                    JavaTemplateId::SwitchArm,
                    &SwitchArmView {
                        indent: &indent(depth + 1),
                        pattern: &pattern,
                        body: &body,
                    },
                    file,
                )?);
            }
            render_template(
                templates,
                JavaTemplateId::Switch,
                &SwitchView {
                    indent: &indentation,
                    value: &value,
                    arms: &rendered_arms,
                },
                file,
            )
        }
        JavaStmt::TryCatch { try_block, catches } => {
            let body = render_block(try_block, names, depth + 1, templates, file)?;
            let mut rendered_catches = String::new();
            for catch in catches {
                let exception_type = render_java_type(&catch.exception_type, names)?;
                let catch_body = render_block(&catch.body, names, depth + 1, templates, file)?;
                rendered_catches.push_str(&render_template(
                    templates,
                    JavaTemplateId::Catch,
                    &CatchView {
                        exception_type: &exception_type,
                        binding: catch.binding.as_str(),
                        body: &catch_body,
                        indent: &indentation,
                    },
                    file,
                )?);
            }
            render_template(
                templates,
                JavaTemplateId::TryCatch,
                &TryCatchView {
                    indent: &indentation,
                    body: &body,
                    catches: &rendered_catches,
                },
                file,
            )
        }
        JavaStmt::ThrowAssertion(message) => {
            let message = render_expr(message, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::Throw,
                &ThrowView {
                    indent: &indentation,
                    message: &message,
                },
                file,
            )
        }
        JavaStmt::Throw(value) => {
            let value = render_expr(value, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::ThrowValue,
                &ExpressionStatementView {
                    indent: &indentation,
                    value: &value,
                },
                file,
            )
        }
        JavaStmt::Break => render_template(
            templates,
            JavaTemplateId::Break,
            &IndentView {
                indent: &indentation,
            },
            file,
        ),
        JavaStmt::Continue => render_template(
            templates,
            JavaTemplateId::Continue,
            &IndentView {
                indent: &indentation,
            },
            file,
        ),
    }
}

#[derive(Serialize)]
struct BlockView<'a> {
    statements: &'a str,
}
#[derive(Serialize)]
struct LocalView<'a> {
    indent: &'a str,
    finality: &'a str,
    ty: &'a str,
    name: &'a str,
    initializer: &'a str,
}
#[derive(Serialize)]
struct AssignView<'a> {
    indent: &'a str,
    target: &'a str,
    value: &'a str,
}
#[derive(Serialize)]
struct ExpressionStatementView<'a> {
    indent: &'a str,
    value: &'a str,
}
#[derive(Serialize)]
struct ReturnView<'a> {
    indent: &'a str,
    value: &'a str,
}
#[derive(Serialize)]
struct IfView<'a> {
    indent: &'a str,
    condition: &'a str,
    then_body: &'a str,
    alternate_body: &'a str,
}
#[derive(Serialize)]
struct ForEachView<'a> {
    indent: &'a str,
    ty: &'a str,
    binding: &'a str,
    iterable: &'a str,
    body: &'a str,
}
#[derive(Serialize)]
struct WhileView<'a> {
    indent: &'a str,
    condition: &'a str,
    body: &'a str,
}
#[derive(Serialize)]
struct SwitchView<'a> {
    indent: &'a str,
    value: &'a str,
    arms: &'a str,
}
#[derive(Serialize)]
struct SwitchArmView<'a> {
    indent: &'a str,
    pattern: &'a str,
    body: &'a str,
}
#[derive(Serialize)]
struct ThrowView<'a> {
    indent: &'a str,
    message: &'a str,
}
#[derive(Serialize)]
struct IndentView<'a> {
    indent: &'a str,
}
#[derive(Serialize)]
struct TryCatchView<'a> {
    indent: &'a str,
    body: &'a str,
    catches: &'a str,
}
#[derive(Serialize)]
struct CatchView<'a> {
    exception_type: &'a str,
    binding: &'a str,
    body: &'a str,
    indent: &'a str,
}

fn render_expr(
    value: &JavaExpr,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    templates: &mut CertifiedTemplateEngine<JavaTemplateId>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    match &value.kind {
        JavaExprKind::Literal(value) => render_template(
            templates,
            JavaTemplateId::Literal,
            &SingleValueView {
                value: &render_literal(value),
            },
            file,
        ),
        JavaExprKind::Value(value) => {
            let value = match value {
                JavaValueRef::Local(value) => value.as_str().to_owned(),
                JavaValueRef::This => "this".to_owned(),
                JavaValueRef::Generated(value) => {
                    resolved_name(names, &TargetSymbolRef::Generated(*value))?
                }
                JavaValueRef::KnownField(value) => {
                    format!(
                        "{}.{}",
                        resolved_type_name(names, value.owner())?,
                        value.member().text()
                    )
                }
            };
            render_template(
                templates,
                JavaTemplateId::Name,
                &SingleValueView { value: &value },
                file,
            )
        }
        JavaExprKind::Unary { operator, operand } => {
            let operand = render_expr(operand, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::Unary,
                &UnaryView {
                    operator: unary_operator(*operator),
                    operand: &operand,
                },
                file,
            )
        }
        JavaExprKind::Binary {
            operator,
            left,
            right,
        } => {
            let left = render_expr(left, names, templates, file)?;
            let right = render_expr(right, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::Binary,
                &BinaryView {
                    left: &left,
                    operator: binary_operator(*operator),
                    right: &right,
                },
                file,
            )
        }
        JavaExprKind::Conditional {
            condition,
            when_true,
            when_false,
        } => {
            let condition = render_expr(condition, names, templates, file)?;
            let when_true = render_expr(when_true, names, templates, file)?;
            let when_false = render_expr(when_false, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::Conditional,
                &ConditionalView {
                    condition: &condition,
                    when_true: &when_true,
                    when_false: &when_false,
                },
                file,
            )
        }
        JavaExprKind::Call {
            callable,
            receiver,
            arguments,
        } => {
            let target = match callable {
                JavaCallableRef::Known {
                    callable: value, ..
                } => {
                    format!(
                        "{}.{}",
                        resolved_type_name(names, value.owner())?,
                        value.name()
                    )
                }
                JavaCallableRef::Runtime { callable, .. } => {
                    resolved_name(names, &TargetSymbolRef::RuntimeCallable(*callable))?
                }
                JavaCallableRef::Generated { symbol, .. } => resolved_name(
                    names,
                    &TargetSymbolRef::Generated(GeneratedSymbolId::Callable(*symbol)),
                )?,
                JavaCallableRef::Interface { symbol, .. } => {
                    let receiver = receiver.as_deref().ok_or_else(|| {
                        vec![render_diagnostic(
                            file,
                            "interface call is missing its receiver",
                        )]
                    })?;
                    format!(
                        "{}.{}",
                        render_expr(receiver, names, templates, file)?,
                        resolved_name(
                            names,
                            &TargetSymbolRef::Generated(GeneratedSymbolId::InterfaceMethod(
                                *symbol
                            )),
                        )?
                    )
                }
                JavaCallableRef::Member { name, .. } => {
                    let receiver = receiver.as_deref().ok_or_else(|| {
                        vec![render_diagnostic(
                            file,
                            "member call is missing its receiver",
                        )]
                    })?;
                    format!(
                        "{}.{}",
                        render_expr(receiver, names, templates, file)?,
                        name.as_str()
                    )
                }
            };
            let arguments = arguments
                .iter()
                .map(|value| render_expr(value, names, templates, file))
                .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
                .join(", ");
            render_template(
                templates,
                JavaTemplateId::Call,
                &CallView {
                    target: &target,
                    arguments: &arguments,
                },
                file,
            )
        }
        JavaExprKind::New {
            constructor,
            arguments,
        } => {
            let target = match constructor {
                JavaConstructorRef::Known {
                    constructor, owner, ..
                } => {
                    let _catalogue_name =
                        resolved_name(names, &TargetSymbolRef::KnownConstructor(*constructor))?;
                    render_java_type(owner, names)?
                }
                JavaConstructorRef::Generated { owner, .. } => resolved_name(
                    names,
                    &TargetSymbolRef::Generated(GeneratedSymbolId::Type(*owner)),
                )?,
            };
            let arguments = arguments
                .iter()
                .map(|value| render_expr(value, names, templates, file))
                .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
                .join(", ");
            render_template(
                templates,
                JavaTemplateId::New,
                &CallView {
                    target: &target,
                    arguments: &arguments,
                },
                file,
            )
        }
        JavaExprKind::NewArray { component, length } => {
            let component = render_java_type(component, names)?;
            let length = render_expr(length, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::NewArray,
                &NewArrayView {
                    component: &component,
                    length: &length,
                },
                file,
            )
        }
        JavaExprKind::ArrayIndex { array, index } => {
            let array = render_expr(array, names, templates, file)?;
            let index = render_expr(index, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::ArrayIndex,
                &ArrayIndexView {
                    array: &array,
                    index: &index,
                },
                file,
            )
        }
        JavaExprKind::Field { receiver, field } => {
            let receiver = render_expr(receiver, names, templates, file)?;
            let field = match field {
                JavaFieldRef::Known(value) => value.member().text(),
                JavaFieldRef::Structural { name, .. } => name.as_str(),
                JavaFieldRef::Generated { name, .. } => name.as_str(),
            };
            render_template(
                templates,
                JavaTemplateId::FieldAccess,
                &FieldAccessView {
                    receiver: &receiver,
                    field,
                },
                file,
            )
        }
        JavaExprKind::Cast { target, value } => {
            let target = render_java_type(target, names)?;
            let value = render_expr(value, names, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::Cast,
                &CastView {
                    target: &target,
                    value: &value,
                },
                file,
            )
        }
        JavaExprKind::InstanceOf {
            value,
            target,
            binding,
        } => {
            let value = render_expr(value, names, templates, file)?;
            let target = render_java_type(target, names)?;
            let binding = binding
                .as_ref()
                .map(|value| format!(" {}", value.as_str()))
                .unwrap_or_default();
            render_template(
                templates,
                JavaTemplateId::InstanceOf,
                &InstanceOfView {
                    value: &value,
                    target: &target,
                    binding: &binding,
                },
                file,
            )
        }
        JavaExprKind::Lambda { parameters, body } => {
            let parameters = parameters
                .iter()
                .map(|value| value.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            let body = render_block(body, names, 1, templates, file)?;
            render_template(
                templates,
                JavaTemplateId::Lambda,
                &LambdaView {
                    parameters: &parameters,
                    body: &body,
                    indent: "",
                },
                file,
            )
        }
    }
}

fn render_java_type(
    value: &JavaType,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
) -> Result<String, Vec<Diagnostic>> {
    match value {
        JavaType::Primitive(value) => Ok(value.keyword().to_owned()),
        JavaType::Boxed(value) => Ok(match value {
            JavaPrimitive::Boolean => "Boolean",
            JavaPrimitive::Byte => "Byte",
            JavaPrimitive::Char => "Character",
            JavaPrimitive::Int => "Integer",
            JavaPrimitive::Long => "Long",
            JavaPrimitive::Double => "Double",
            JavaPrimitive::Void => "Void",
        }
        .to_owned()),
        JavaType::Reference(JavaTypeName::Known(value)) => resolved_type_name(names, *value),
        JavaType::Reference(JavaTypeName::Generated(value)) => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::Type(*value)),
        ),
        JavaType::Array { component, .. } => {
            Ok(format!("{}[]", render_java_type(component, names)?))
        }
        JavaType::Generic { raw, arguments } => {
            let raw = match raw {
                JavaTypeName::Known(value) => resolved_type_name(names, *value)?,
                JavaTypeName::Generated(value) => resolved_name(
                    names,
                    &TargetSymbolRef::Generated(GeneratedSymbolId::Type(*value)),
                )?,
            };
            let arguments = arguments
                .iter()
                .map(|value| render_java_type(value, names))
                .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
                .join(", ");
            Ok(format!("{raw}<{arguments}>"))
        }
        JavaType::Wildcard { bound: None } => Ok("?".to_owned()),
        JavaType::Wildcard {
            bound: Some((kind, ty)),
        } => Ok(format!(
            "? {} {}",
            match kind {
                JavaWildcardBound::Extends => "extends",
                JavaWildcardBound::Super => "super",
            },
            render_java_type(ty, names)?
        )),
        JavaType::TypeVariable(value) => Ok(value.as_str().to_owned()),
    }
}

fn resolved_type_name(
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    value: JavaKnownType,
) -> Result<String, Vec<Diagnostic>> {
    resolved_name(names, &TargetSymbolRef::KnownType(value))
}

fn resolved_name(
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    symbol: &TargetSymbolRef<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    names
        .get(symbol)
        .map(|value| match value {
            JavaResolvedName::Local(value) => value.as_str().to_owned(),
            JavaResolvedName::Qualified(value) => value.text().to_owned(),
            JavaResolvedName::GeneratedMember { owner, member } => {
                format!("{}.{}", owner.text(), member.as_str())
            }
            JavaResolvedName::Member { owner, member } => {
                format!("{}.{}", owner.text(), member.text())
            }
        })
        .ok_or_else(|| {
            vec![Diagnostic::error(
                DiagnosticCode::UnresolvedReference,
                "renderer received a symbol without a linker-owned spelling",
                portable_diagnostics::SourceRef::logical(["java-renderer", "symbol"]),
            )]
        })
}

fn render_literal(value: &JavaLiteral) -> String {
    match value {
        JavaLiteral::Boolean(value) => value.to_string(),
        JavaLiteral::I32(value) => value.to_string(),
        JavaLiteral::I64(value) => format!("{value}L"),
        JavaLiteral::CharScalar(value) => char::from_u32(*value)
            .map(|value| java_string(&value.to_string()))
            .unwrap_or_else(|| "\"\\ufffd\"".to_owned()),
        JavaLiteral::String(value) => java_string(value),
        JavaLiteral::Utf16Units(values) => {
            let mut result = String::from("\"");
            for value in values {
                result.push_str(&format!("\\u{value:04x}"));
            }
            result.push('"');
            result
        }
        JavaLiteral::InternalNull(_) => "null".to_owned(),
    }
}

fn java_string(value: &str) -> String {
    let mut result = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            ch if ch.is_control() => result.push_str(&format!("\\u{:04x}", u32::from(ch))),
            ch => result.push(ch),
        }
    }
    result.push('"');
    result
}

fn render_heritage(
    value: &JavaHeritage,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
) -> Result<String, Vec<Diagnostic>> {
    match value {
        JavaHeritage::None => Ok(String::new()),
        JavaHeritage::Interfaces(values) => values
            .iter()
            .map(|value| render_java_type(value, names))
            .collect::<Result<Vec<_>, Vec<Diagnostic>>>()
            .map(|values| format!(" implements {}", values.join(", "))),
        JavaHeritage::ExternalAdapter { .. } => Ok(" extends ApprovedFrameworkAdapter".to_owned()),
        JavaHeritage::InternalRuntime(JavaInternalBase::RuntimeException) => Ok(format!(
            " extends {}",
            resolved_type_name(names, JavaKnownType::RuntimeException)?
        )),
    }
}

fn visibility(value: JavaVisibility, trailing: bool) -> &'static str {
    match (value, trailing) {
        (JavaVisibility::Public, true) => "public ",
        (JavaVisibility::Private, true) => "private ",
        (JavaVisibility::Package, true) => "",
        _ => "",
    }
}

fn modifiers(values: &[JavaModifier]) -> String {
    values
        .iter()
        .map(|value| match value {
            JavaModifier::Public => "public ",
            JavaModifier::Private => "private ",
            JavaModifier::Static => "static ",
            JavaModifier::Final => "final ",
            JavaModifier::Transient => "transient ",
            JavaModifier::Sealed => "sealed ",
            JavaModifier::NonSealed => "non-sealed ",
            JavaModifier::Abstract => "abstract ",
        })
        .collect()
}

fn render_type_parameters(values: &[JavaIdentifier]) -> String {
    if values.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            values
                .iter()
                .map(JavaIdentifier::as_str)
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn render_method_type_parameters(values: &[JavaIdentifier]) -> String {
    let value = render_type_parameters(values);
    if value.is_empty() {
        value
    } else {
        format!("{value} ")
    }
}

fn indent(depth: usize) -> String {
    "  ".repeat(depth)
}

fn unary_operator(value: JavaUnaryOperator) -> &'static str {
    match value {
        JavaUnaryOperator::Not => "!",
        JavaUnaryOperator::Negate => "-",
        JavaUnaryOperator::BitNot => "~",
    }
}

fn binary_operator(value: JavaBinaryOperator) -> &'static str {
    match value {
        JavaBinaryOperator::LogicalAnd => "&&",
        JavaBinaryOperator::LogicalOr => "||",
        JavaBinaryOperator::Equal => "==",
        JavaBinaryOperator::NotEqual => "!=",
        JavaBinaryOperator::Less => "<",
        JavaBinaryOperator::LessEqual => "<=",
        JavaBinaryOperator::Greater => ">",
        JavaBinaryOperator::GreaterEqual => ">=",
        JavaBinaryOperator::Add => "+",
        JavaBinaryOperator::Subtract => "-",
        JavaBinaryOperator::Multiply => "*",
        JavaBinaryOperator::Divide => "/",
        JavaBinaryOperator::Remainder => "%",
        JavaBinaryOperator::BitAnd => "&",
        JavaBinaryOperator::BitOr => "|",
        JavaBinaryOperator::BitXor => "^",
        JavaBinaryOperator::ShiftLeft => "<<",
        JavaBinaryOperator::ShiftRight => ">>",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn strict_template_registry_is_exact_and_exhaustive() {
        let templates = java_templates();
        assert_eq!(templates.len(), JavaTemplateId::ALL.len());
        let ids = JavaTemplateId::ALL.iter().collect::<BTreeSet<_>>();
        assert_eq!(ids.len(), JavaTemplateId::ALL.len());
        // Every generated package test also constructs the strict registry;
        // its private validator rejects missing, duplicate, or extra entries.
    }
}

#[derive(Serialize)]
struct SingleValueView<'a> {
    value: &'a str,
}
#[derive(Serialize)]
struct UnaryView<'a> {
    operator: &'a str,
    operand: &'a str,
}
#[derive(Serialize)]
struct BinaryView<'a> {
    left: &'a str,
    operator: &'a str,
    right: &'a str,
}
#[derive(Serialize)]
struct ConditionalView<'a> {
    condition: &'a str,
    when_true: &'a str,
    when_false: &'a str,
}
#[derive(Serialize)]
struct CallView<'a> {
    target: &'a str,
    arguments: &'a str,
}
#[derive(Serialize)]
struct FieldAccessView<'a> {
    receiver: &'a str,
    field: &'a str,
}
#[derive(Serialize)]
struct CastView<'a> {
    target: &'a str,
    value: &'a str,
}
#[derive(Serialize)]
struct InstanceOfView<'a> {
    value: &'a str,
    target: &'a str,
    binding: &'a str,
}
#[derive(Serialize)]
struct NewArrayView<'a> {
    component: &'a str,
    length: &'a str,
}
#[derive(Serialize)]
struct ArrayIndexView<'a> {
    array: &'a str,
    index: &'a str,
}
#[derive(Serialize)]
struct LambdaView<'a> {
    parameters: &'a str,
    body: &'a str,
    indent: &'a str,
}
