use crate::ast::{JavaFileItem, JavaFilePlacement};
use crate::dialect::JavaDialect;
use declarations::{render_member, render_type, render_type_with_extra};
use portable_codegen::{CertifiedSourceFile, LinkedFile, TotalSourceRenderer};
use portable_diagnostics::{Diagnostic, DiagnosticCode};
mod declarations;

mod statements;

mod expressions;

mod names;

mod syntax;

#[derive(Clone, Copy, Debug, Default)]
pub struct JavaRenderer;

impl TotalSourceRenderer<JavaDialect> for JavaRenderer {
    fn target_name(&self) -> &'static str {
        "org.polyrust.java"
    }

    fn render_file(&self, certified: CertifiedSourceFile<'_, JavaDialect>) -> String {
        let file = certified.file();
        render_java_file(file).unwrap_or_else(|diagnostics| {
            panic!("render-ready Java package violated its certificate: {diagnostics:#?}")
        })
    }
}

fn render_java_file(file: &LinkedFile<JavaDialect>) -> Result<String, Vec<Diagnostic>> {
    let mut output = String::from("// Generated by PolyRust from verified CoreIR.\n");
    output.push_str("package ");
    output.push_str(file.module().name());
    output.push_str(";\n\n");
    for import in file.imports() {
        output.push_str("import ");
        output.push_str(import.kind().qualified_name());
        output.push_str(";\n");
    }
    if !file.imports().is_empty() {
        output.push('\n');
    }

    let declarations = if *file.placement() == JavaFilePlacement::Runtime {
        render_runtime_file(file)?
    } else {
        let mut declarations = String::new();
        for item in file.items() {
            match &item.item {
                JavaFileItem::Type { declaration, .. } => {
                    declarations.push_str(&render_type(declaration, &item.names, 0, file)?);
                }
                JavaFileItem::RuntimeMembers { .. } => {
                    return Err(vec![render_diagnostic(
                        file,
                        "runtime member fragment appeared outside the runtime file",
                    )]);
                }
            }
        }
        declarations
    };
    output.push_str(&declarations);
    Ok(output)
}

fn render_runtime_file(file: &LinkedFile<JavaDialect>) -> Result<String, Vec<Diagnostic>> {
    let mut shell = None;
    let mut extra = String::new();
    for item in file.items() {
        match &item.item {
            JavaFileItem::Type { declaration, .. } => {
                if shell.replace((declaration, &item.names)).is_some() {
                    return Err(vec![render_diagnostic(
                        file,
                        "runtime file has multiple class shells",
                    )]);
                }
            }
            JavaFileItem::RuntimeMembers { members, .. } => {
                for member in members {
                    extra.push_str(&render_member(member, &item.names, 1, file)?);
                }
            }
        }
    }
    let Some((shell, names)) = shell else {
        return Err(vec![render_diagnostic(
            file,
            "runtime file has no typed class shell",
        )]);
    };
    render_type_with_extra(shell, names, 0, &extra, file)
}

fn render_diagnostic(file: &LinkedFile<JavaDialect>, message: &str) -> Diagnostic {
    Diagnostic::error(
        DiagnosticCode::InvalidStructure,
        message,
        file.source().clone(),
    )
}

#[cfg(test)]
#[path = "tests/render.rs"]
mod tests;
