use portable_codegen::{
    CertifiedSourceFile, GeneratedSymbolId, LinkedFile, TargetSymbolRef, TotalSourceRenderer,
};
use portable_diagnostics::{Diagnostic, DiagnosticCode};

use crate::{ast::*, dialect::*};

#[derive(Clone, Copy, Debug, Default)]
pub struct JavaRenderer;

impl TotalSourceRenderer<JavaDialect> for JavaRenderer {
    fn target_name(&self) -> &'static str {
        "org.polyrust.java"
    }

    fn render_file(&self, certified: CertifiedSourceFile<'_, JavaDialect>) -> String {
        let file = certified.file();
        render_java_file(file).unwrap_or_else(|diagnostics| {
            panic!("render-ready Java package violated its certificate: {diagnostics:#?}")
        })
    }
}

fn render_java_file(file: &LinkedFile<JavaDialect>) -> Result<String, Vec<Diagnostic>> {
    let mut output = String::from("// Generated by PolyRust from verified CoreIR.\n");
    output.push_str("package ");
    output.push_str(file.module().name());
    output.push_str(";\n\n");
    for import in file.imports() {
        output.push_str("import ");
        output.push_str(import.kind().qualified_name());
        output.push_str(";\n");
    }
    if !file.imports().is_empty() {
        output.push('\n');
    }

    let declarations = if *file.placement() == JavaFilePlacement::Runtime {
        render_runtime_file(file)?
    } else {
        let mut declarations = String::new();
        for item in file.items() {
            match &item.item {
                JavaFileItem::Type { declaration, .. } => {
                    declarations.push_str(&render_type(declaration, &item.names, 0, file)?);
                }
                JavaFileItem::RuntimeMembers { .. } => {
                    return Err(vec![render_diagnostic(
                        file,
                        "runtime member fragment appeared outside the runtime file",
                    )]);
                }
            }
        }
        declarations
    };
    output.push_str(&declarations);
    Ok(output)
}

fn render_runtime_file(file: &LinkedFile<JavaDialect>) -> Result<String, Vec<Diagnostic>> {
    let mut shell = None;
    let mut extra = String::new();
    for item in file.items() {
        match &item.item {
            JavaFileItem::Type { declaration, .. } => {
                if shell.replace((declaration, &item.names)).is_some() {
                    return Err(vec![render_diagnostic(
                        file,
                        "runtime file has multiple class shells",
                    )]);
                }
            }
            JavaFileItem::RuntimeMembers { members, .. } => {
                for member in members {
                    extra.push_str(&render_member(member, &item.names, 1, file)?);
                }
            }
        }
    }
    let Some((shell, names)) = shell else {
        return Err(vec![render_diagnostic(
            file,
            "runtime file has no typed class shell",
        )]);
    };
    render_type_with_extra(shell, names, 0, &extra, file)
}

fn render_diagnostic(file: &LinkedFile<JavaDialect>, message: &str) -> Diagnostic {
    Diagnostic::error(
        DiagnosticCode::InvalidStructure,
        message,
        file.source().clone(),
    )
}

fn render_type(
    value: &JavaTypeDeclaration,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    render_type_with_extra(value, names, depth, "", file)
}

fn render_type_with_extra(
    value: &JavaTypeDeclaration,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    extra_members: &str,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indent = indent(depth);
    let visibility = visibility(value.visibility);
    let declaration_modifiers = modifiers(&value.modifiers);
    let type_parameters = render_type_parameters(&value.type_parameters);
    let declaration_name = match value.declared {
        Some(symbol) => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::Type(symbol)),
        )?,
        None => value.name.as_str().to_owned(),
    };
    let heritage = render_heritage(&value.heritage, names)?;
    let mut members = String::new();
    let mut enum_constants = Vec::new();
    for member in &value.members {
        if let JavaMember::EnumConstant(constant) = member {
            enum_constants.push(render_enum_constant(constant, names)?);
        } else {
            members.push_str(&render_member(member, names, depth + 1, file)?);
        }
    }
    members.push_str(extra_members);
    let components = value
        .record_components
        .iter()
        .map(|component| {
            Ok(format!(
                "{} {}",
                render_java_type(&component.ty, names)?,
                component.name.as_str()
            ))
        })
        .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
        .join(", ");
    let permits = value
        .permits
        .iter()
        .map(|ty| render_java_type(ty, names))
        .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
        .join(", ");
    match value.kind {
        JavaDeclarationKind::FinalClass => Ok(format!(
            "{indent}{visibility}{declaration_modifiers}final class {declaration_name}{type_parameters}{heritage} {{\n{members}{indent}}}\n"
        )),
        JavaDeclarationKind::Record => Ok(format!(
            "{indent}{visibility}{declaration_modifiers}record {declaration_name}{type_parameters}({components}){heritage} {{\n{members}{indent}}}\n"
        )),
        JavaDeclarationKind::Enum => {
            let constants = enum_constants.join(",\n");
            let constants = constants
                .lines()
                .map(|line| format!("{}{}", "    ".repeat(depth + 1), line))
                .collect::<Vec<_>>()
                .join("\n");
            Ok(format!(
                "{indent}{visibility}{declaration_modifiers}enum {declaration_name} {{\n{constants};\n{members}{indent}}}\n"
            ))
        }
        JavaDeclarationKind::Interface => Ok(format!(
            "{indent}{visibility}{declaration_modifiers}interface {declaration_name}{type_parameters} {{\n{members}{indent}}}\n"
        )),
        JavaDeclarationKind::SealedInterface => Ok(format!(
            "{indent}{visibility}{declaration_modifiers}sealed interface {declaration_name}{type_parameters} permits {permits} {{\n{members}{indent}}}\n"
        )),
    }
}

fn render_member(
    value: &JavaMember,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    match value {
        JavaMember::Field(value) => render_field(value, names, depth, file),
        JavaMember::CompileFailField(value) => {
            let field = JavaField {
                declared: None,
                modifiers: value.modifiers.clone(),
                ty: value.expected_type.clone(),
                name: value.name.clone(),
                initializer: Some(value.initializer.clone()),
            };
            render_field(&field, names, depth, file)
        }
        JavaMember::EnumConstant(value) => Ok(format!(
            "{}{}\n",
            indent(depth),
            render_enum_constant(value, names)?
        )),
        JavaMember::Method(value) => render_method(value, names, depth, file),
        JavaMember::Constructor(value) => render_constructor(value, names, depth, file),
        JavaMember::NestedType(value) => render_type(value, names, depth, file),
    }
}

fn render_enum_constant(
    value: &crate::ast::JavaEnumConstant,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
) -> Result<String, Vec<Diagnostic>> {
    resolved_generated_member_name(names, GeneratedSymbolId::Value(value.declared))
}

fn render_field(
    value: &JavaField,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indent = indent(depth);
    let modifiers = modifiers(&value.modifiers);
    let ty = render_java_type(&value.ty, names)?;
    let initializer = match &value.initializer {
        Some(value) => format!(" = {}", render_expr(value, names, file)?),
        None => String::new(),
    };
    let field_name = match value.declared {
        Some(symbol) => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::Value(symbol)),
        )?,
        None => value.name.as_str().to_owned(),
    };
    Ok(format!(
        "{indent}{modifiers}{ty} {field_name}{initializer};\n"
    ))
}

fn render_method(
    value: &JavaMethod,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indent = indent(depth);
    let annotations = render_annotations(&value.annotations, depth);
    let modifiers = modifiers(&value.modifiers);
    let type_parameters = render_method_type_parameters(&value.type_parameters);
    let return_type = render_java_type(&value.return_type, names)?;
    let parameters = render_parameters(&value.parameters, names)?;
    let method_name = match value.declared {
        JavaMethodDeclaration::Callable(symbol) => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::Callable(symbol)),
        )?,
        JavaMethodDeclaration::Interface(symbol)
        | JavaMethodDeclaration::Implementation {
            interface: symbol, ..
        } => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::InterfaceMethod(symbol)),
        )?,
        JavaMethodDeclaration::Structural => value.name.as_str().to_owned(),
    };
    match &value.body {
        Some(body) => {
            let body = render_block(body, names, depth + 1, file)?;
            Ok(format!(
                "{annotations}{indent}{modifiers}{type_parameters}{return_type} {method_name}({parameters}) {{\n{body}{indent}}}\n"
            ))
        }
        None => Ok(format!(
            "{annotations}{indent}{modifiers}{type_parameters}{return_type} {method_name}({parameters});\n"
        )),
    }
}

fn render_constructor(
    value: &JavaConstructor,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indent = indent(depth);
    let modifiers = modifiers(&value.modifiers);
    let parameters = render_parameters(&value.parameters, names)?;
    let body = render_block(&value.body, names, depth + 1, file)?;
    Ok(format!(
        "{indent}{modifiers}{}({parameters}) {{\n{body}{indent}}}\n",
        value.name.as_str()
    ))
}

fn render_annotations(values: &[JavaAnnotation], depth: usize) -> String {
    let mut output = String::new();
    let indent = indent(depth);
    for value in values {
        let name = match value {
            JavaAnnotation::Override => "Override",
            JavaAnnotation::SafeVarargs => "SafeVarargs",
        };
        output.push_str(&format!("{indent}@{name}\n"));
    }
    output
}

fn render_parameters(
    values: &[JavaParameter],
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
) -> Result<String, Vec<Diagnostic>> {
    values
        .iter()
        .map(|value| {
            let ty = render_java_type(&value.ty, names)?;
            Ok(format!(
                "{}{ty} {}",
                if value.final_parameter { "final " } else { "" },
                value.name.as_str()
            ))
        })
        .collect::<Result<Vec<_>, Vec<Diagnostic>>>()
        .map(|values| values.join(", "))
}

fn render_block(
    value: &JavaBlock,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let mut statements = String::new();
    for statement in &value.statements {
        statements.push_str(&render_stmt(statement, names, depth, file)?);
    }
    Ok(statements)
}

fn render_stmt(
    value: &JavaStmt,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    depth: usize,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    let indentation = indent(depth);
    match value {
        JavaStmt::Local {
            finality,
            ty,
            name,
            value,
        } => {
            let ty = render_java_type(ty, names)?;
            let initializer = match value {
                Some(value) => format!(" = {}", render_expr(value, names, file)?),
                None => String::new(),
            };
            let finality = if *finality == JavaLocalFinality::Final {
                "final "
            } else {
                ""
            };
            Ok(format!(
                "{indentation}{finality}{ty} {}{initializer};\n",
                name.as_str()
            ))
        }
        JavaStmt::Assign { target, value } => {
            let target = render_expr(target, names, file)?;
            let value = render_expr(value, names, file)?;
            Ok(format!("{indentation}{target} = {value};\n"))
        }
        JavaStmt::Expression(value) => {
            let value = render_expr(value, names, file)?;
            Ok(format!("{indentation}{value};\n"))
        }
        JavaStmt::Return(value) => {
            let value = match value {
                Some(value) => format!(" {}", render_expr(value, names, file)?),
                None => String::new(),
            };
            Ok(format!("{indentation}return{value};\n"))
        }
        JavaStmt::If {
            condition,
            then_block,
            else_block,
        } => {
            let condition = render_expr(condition, names, file)?;
            let then_body = render_block(then_block, names, depth + 1, file)?;
            let else_body = match else_block {
                Some(value) => format!(
                    " else {{\n{}{}}}",
                    render_block(value, names, depth + 1, file)?,
                    indentation
                ),
                None => String::new(),
            };
            Ok(format!(
                "{indentation}if ({condition}) {{\n{then_body}{indentation} }}{else_body}\n"
            ))
        }
        JavaStmt::ForEach {
            binding_type,
            binding,
            iterable,
            body,
        } => {
            let ty = render_java_type(binding_type, names)?;
            let iterable = render_expr(iterable, names, file)?;
            let body = render_block(body, names, depth + 1, file)?;
            Ok(format!(
                "{indentation}for ({ty} {} : {iterable}) {{\n{body}{indentation}}}\n",
                binding.as_str()
            ))
        }
        JavaStmt::While { condition, body } => {
            let condition = render_expr(condition, names, file)?;
            let body = render_block(body, names, depth + 1, file)?;
            Ok(format!(
                "{indentation}while ({condition}) {{\n{body}{indentation}}}\n"
            ))
        }
        JavaStmt::Switch { value, arms } => {
            let value = render_expr(value, names, file)?;
            let mut rendered_arms = String::new();
            for arm in arms {
                let pattern = render_switch_pattern(&arm.pattern, names)?;
                let body = render_block(&arm.body, names, depth + 2, file)?;
                let arm_indent = indent(depth + 1);
                rendered_arms.push_str(&format!(
                    "{arm_indent}{pattern} -> {{\n{body}{arm_indent}}}\n"
                ));
            }
            Ok(format!(
                "{indentation}switch ({value}) {{\n{rendered_arms}{indentation}}}\n"
            ))
        }
        JavaStmt::TryCatch { try_block, catches } => {
            let body = render_block(try_block, names, depth + 1, file)?;
            let mut rendered_catches = String::new();
            for catch in catches {
                let exception_type = render_java_type(&catch.exception_type, names)?;
                let catch_body = render_block(&catch.body, names, depth + 1, file)?;
                rendered_catches.push_str(&format!(
                    " catch ({exception_type} {}) {{\n{catch_body}{indentation} }}",
                    catch.binding.as_str()
                ));
            }
            Ok(format!(
                "{indentation}try {{\n{body}{indentation} }}{rendered_catches}\n"
            ))
        }
        JavaStmt::ThrowAssertion(message) => {
            let message = render_expr(message, names, file)?;
            Ok(format!(
                "{indentation}throw new AssertionError({message});\n"
            ))
        }
        JavaStmt::Throw(value) => {
            let value = render_expr(value, names, file)?;
            Ok(format!("{indentation}throw {value};\n"))
        }
        JavaStmt::Break => Ok(format!("{indentation}break;\n")),
        JavaStmt::Continue => Ok(format!("{indentation}continue;\n")),
    }
}

fn render_switch_pattern(
    pattern: &JavaPattern,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
) -> Result<String, Vec<Diagnostic>> {
    match pattern {
        JavaPattern::Default => Ok("default".to_owned()),
        JavaPattern::Literal(value) => Ok(format!("case {}", render_literal(value))),
        JavaPattern::EnumVariant { variant, .. } => Ok(format!(
            "case {}",
            resolved_generated_member_name(names, GeneratedSymbolId::Value(*variant))?
        )),
        JavaPattern::Type { ty, binding } => Ok(format!(
            "case {} {}",
            render_java_type(ty, names)?,
            binding.as_str()
        )),
    }
}

fn render_expr(
    value: &JavaExpr,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    file: &LinkedFile<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    match &value.kind {
        JavaExprKind::Literal(value) => Ok(render_literal(value)),
        JavaExprKind::Value(value) => {
            let value = match value {
                JavaValueRef::Local(value) => value.as_str().to_owned(),
                JavaValueRef::This => "this".to_owned(),
                JavaValueRef::Generated(value) => {
                    resolved_name(names, &TargetSymbolRef::Generated(*value))?
                }
                JavaValueRef::EnumVariant {
                    enumeration,
                    variant,
                } => format!(
                    "{}.{}",
                    resolved_name(
                        names,
                        &TargetSymbolRef::Generated(GeneratedSymbolId::Type(*enumeration)),
                    )?,
                    resolved_generated_member_name(names, GeneratedSymbolId::Value(*variant))?
                ),
                JavaValueRef::KnownField(value) => {
                    format!(
                        "{}.{}",
                        resolved_type_name(names, value.owner())?,
                        value.member().text()
                    )
                }
            };
            Ok(value)
        }
        JavaExprKind::Unary { operator, operand } => {
            let operand = render_expr(operand, names, file)?;
            Ok(format!("({}{operand})", unary_operator(*operator)))
        }
        JavaExprKind::Binary {
            operator,
            left,
            right,
        } => {
            let left = render_expr(left, names, file)?;
            let right = render_expr(right, names, file)?;
            Ok(format!("({left} {} {right})", binary_operator(*operator)))
        }
        JavaExprKind::Conditional {
            condition,
            when_true,
            when_false,
        } => {
            let condition = render_expr(condition, names, file)?;
            let when_true = render_expr(when_true, names, file)?;
            let when_false = render_expr(when_false, names, file)?;
            Ok(format!("({condition} ? {when_true} : {when_false})"))
        }
        JavaExprKind::Call {
            callable,
            receiver,
            arguments,
        } => {
            let target = match callable {
                JavaCallableRef::Known {
                    callable: value, ..
                } => {
                    format!(
                        "{}.{}",
                        resolved_type_name(names, value.owner())?,
                        value.name()
                    )
                }
                JavaCallableRef::Runtime { callable, .. } => {
                    resolved_name(names, &TargetSymbolRef::RuntimeCallable(*callable))?
                }
                JavaCallableRef::Generated { symbol, .. } => resolved_name(
                    names,
                    &TargetSymbolRef::Generated(GeneratedSymbolId::Callable(*symbol)),
                )?,
                JavaCallableRef::Interface { symbol, .. } => {
                    let receiver = receiver.as_deref().ok_or_else(|| {
                        vec![render_diagnostic(
                            file,
                            "interface call is missing its receiver",
                        )]
                    })?;
                    format!(
                        "{}.{}",
                        render_expr(receiver, names, file)?,
                        resolved_name(
                            names,
                            &TargetSymbolRef::Generated(GeneratedSymbolId::InterfaceMethod(
                                *symbol
                            )),
                        )?
                    )
                }
                JavaCallableRef::Member { name, .. } => {
                    let receiver = receiver.as_deref().ok_or_else(|| {
                        vec![render_diagnostic(
                            file,
                            "member call is missing its receiver",
                        )]
                    })?;
                    format!("{}.{}", render_expr(receiver, names, file)?, name.as_str())
                }
            };
            let arguments = arguments
                .iter()
                .map(|value| render_expr(value, names, file))
                .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
                .join(", ");
            Ok(format!("{target}({arguments})"))
        }
        JavaExprKind::New {
            constructor,
            arguments,
        } => {
            let target = match constructor {
                JavaConstructorRef::Known {
                    constructor, owner, ..
                } => {
                    let _catalogue_name =
                        resolved_name(names, &TargetSymbolRef::KnownConstructor(*constructor))?;
                    render_java_type(owner, names)?
                }
                JavaConstructorRef::Generated { owner, .. } => resolved_name(
                    names,
                    &TargetSymbolRef::Generated(GeneratedSymbolId::Type(*owner)),
                )?,
            };
            let arguments = arguments
                .iter()
                .map(|value| render_expr(value, names, file))
                .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
                .join(", ");
            Ok(format!("new {target}({arguments})"))
        }
        JavaExprKind::NewArray { component, length } => {
            let component = render_java_type(component, names)?;
            let length = render_expr(length, names, file)?;
            Ok(format!("new {component}[{length}]"))
        }
        JavaExprKind::ArrayIndex { array, index } => {
            let array = render_expr(array, names, file)?;
            let index = render_expr(index, names, file)?;
            Ok(format!("{array}[{index}]"))
        }
        JavaExprKind::Field { receiver, field } => {
            let receiver = render_expr(receiver, names, file)?;
            let field = match field {
                JavaFieldRef::Known(value) => value.member().text(),
                JavaFieldRef::Structural { name, .. } => name.as_str(),
                JavaFieldRef::Generated { name, .. } => name.as_str(),
            };
            Ok(format!("{receiver}.{field}"))
        }
        JavaExprKind::Cast { target, value } => {
            let target = render_java_type(target, names)?;
            let value = render_expr(value, names, file)?;
            Ok(format!("(({target}) {value})"))
        }
        JavaExprKind::ArrayOwnershipTransition { value, .. } => render_expr(value, names, file),
        JavaExprKind::InstanceOf {
            value,
            target,
            binding,
        } => {
            let value = render_expr(value, names, file)?;
            let target = render_java_type(target, names)?;
            let binding = binding
                .as_ref()
                .map(|value| format!(" {}", value.as_str()))
                .unwrap_or_default();
            Ok(format!("({value} instanceof {target}{binding})"))
        }
        JavaExprKind::Lambda { parameters, body } => {
            let parameters = parameters
                .iter()
                .map(|value| value.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            let body = render_block(body, names, 1, file)?;
            Ok(format!("({parameters}) -> {{\n{body} }}"))
        }
    }
}

fn render_java_type(
    value: &JavaType,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
) -> Result<String, Vec<Diagnostic>> {
    match value {
        JavaType::Primitive(value) => Ok(value.keyword().to_owned()),
        JavaType::Boxed(value) => Ok(match value {
            JavaPrimitive::Boolean => "Boolean",
            JavaPrimitive::Byte => "Byte",
            JavaPrimitive::Char => "Character",
            JavaPrimitive::Int => "Integer",
            JavaPrimitive::Long => "Long",
            JavaPrimitive::Double => "Double",
            JavaPrimitive::Void => "Void",
        }
        .to_owned()),
        JavaType::Reference(JavaTypeName::Known(value)) => resolved_type_name(names, *value),
        JavaType::Reference(JavaTypeName::Generated(value)) => resolved_name(
            names,
            &TargetSymbolRef::Generated(GeneratedSymbolId::Type(*value)),
        ),
        JavaType::Array { component, .. } => {
            Ok(format!("{}[]", render_java_type(component, names)?))
        }
        JavaType::Generic { raw, arguments } => {
            let raw = match raw {
                JavaTypeName::Known(value) => resolved_type_name(names, *value)?,
                JavaTypeName::Generated(value) => resolved_name(
                    names,
                    &TargetSymbolRef::Generated(GeneratedSymbolId::Type(*value)),
                )?,
            };
            let arguments = arguments
                .iter()
                .map(|value| render_java_type(value, names))
                .collect::<Result<Vec<_>, Vec<Diagnostic>>>()?
                .join(", ");
            Ok(format!("{raw}<{arguments}>"))
        }
        JavaType::Wildcard { bound: None } => Ok("?".to_owned()),
        JavaType::Wildcard {
            bound: Some((kind, ty)),
        } => Ok(format!(
            "? {} {}",
            match kind {
                JavaWildcardBound::Extends => "extends",
                JavaWildcardBound::Super => "super",
            },
            render_java_type(ty, names)?
        )),
        JavaType::TypeVariable(value) => Ok(value.as_str().to_owned()),
    }
}

fn resolved_type_name(
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    value: JavaKnownType,
) -> Result<String, Vec<Diagnostic>> {
    resolved_name(names, &TargetSymbolRef::KnownType(value))
}

fn resolved_name(
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    symbol: &TargetSymbolRef<JavaDialect>,
) -> Result<String, Vec<Diagnostic>> {
    names
        .get(symbol)
        .map(|value| match value {
            JavaResolvedName::Local(value) => value.as_str().to_owned(),
            JavaResolvedName::Qualified(value) => value.text().to_owned(),
            JavaResolvedName::GeneratedMember { owner, member } => {
                format!("{}.{}", owner.text(), member.as_str())
            }
            JavaResolvedName::Member { owner, member } => {
                format!("{}.{}", owner.text(), member.text())
            }
        })
        .ok_or_else(|| {
            vec![Diagnostic::error(
                DiagnosticCode::UnresolvedReference,
                "renderer received a symbol without a linker-owned spelling",
                portable_diagnostics::SourceRef::logical(["java-renderer", "symbol"]),
            )]
        })
}

fn resolved_generated_member_name(
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
    symbol: GeneratedSymbolId,
) -> Result<String, Vec<Diagnostic>> {
    names
        .get(&TargetSymbolRef::Generated(symbol))
        .and_then(|value| match value {
            JavaResolvedName::Local(value)
            | JavaResolvedName::GeneratedMember { member: value, .. } => {
                Some(value.as_str().to_owned())
            }
            JavaResolvedName::Qualified(_) | JavaResolvedName::Member { .. } => None,
        })
        .ok_or_else(|| {
            vec![Diagnostic::error(
                DiagnosticCode::UnresolvedReference,
                "renderer received a generated member without a member spelling",
                portable_diagnostics::SourceRef::logical(["java-renderer", "generated-member"]),
            )]
        })
}

fn render_literal(value: &JavaLiteral) -> String {
    match value {
        JavaLiteral::Boolean(value) => value.to_string(),
        JavaLiteral::I32(value) => value.to_string(),
        JavaLiteral::I64(value) => format!("{value}L"),
        JavaLiteral::CharScalar(value) => value.to_string(),
        JavaLiteral::String(value) => java_string(value),
        JavaLiteral::Utf16Units(values) => {
            let mut result = String::from("\"");
            for value in values {
                result.push_str(&format!("\\u{value:04x}"));
            }
            result.push('"');
            result
        }
        JavaLiteral::InternalNull(_) => "null".to_owned(),
    }
}

fn java_string(value: &str) -> String {
    let mut result = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            ch if ch.is_control() => result.push_str(&format!("\\u{:04x}", u32::from(ch))),
            ch => result.push(ch),
        }
    }
    result.push('"');
    result
}

fn render_heritage(
    value: &JavaHeritage,
    names: &std::collections::BTreeMap<TargetSymbolRef<JavaDialect>, JavaResolvedName>,
) -> Result<String, Vec<Diagnostic>> {
    match value {
        JavaHeritage::None => Ok(String::new()),
        JavaHeritage::Interfaces(values) => values
            .iter()
            .map(|value| render_java_type(value, names))
            .collect::<Result<Vec<_>, Vec<Diagnostic>>>()
            .map(|values| format!(" implements {}", values.join(", "))),
    }
}

fn visibility(value: JavaVisibility) -> &'static str {
    match value {
        JavaVisibility::Public => "public ",
        JavaVisibility::Private => "private ",
        JavaVisibility::Package => "",
    }
}

fn modifiers(values: &[JavaModifier]) -> String {
    values
        .iter()
        .map(|value| match value {
            JavaModifier::Public => "public ",
            JavaModifier::Private => "private ",
            JavaModifier::Static => "static ",
            JavaModifier::Final => "final ",
            JavaModifier::Transient => "transient ",
            JavaModifier::Sealed => "sealed ",
            JavaModifier::NonSealed => "non-sealed ",
            JavaModifier::Abstract => "abstract ",
        })
        .collect()
}

fn render_type_parameters(values: &[JavaIdentifier]) -> String {
    if values.is_empty() {
        String::new()
    } else {
        format!(
            "<{}>",
            values
                .iter()
                .map(JavaIdentifier::as_str)
                .collect::<Vec<_>>()
                .join(", ")
        )
    }
}

fn render_method_type_parameters(values: &[JavaIdentifier]) -> String {
    let value = render_type_parameters(values);
    if value.is_empty() {
        value
    } else {
        format!("{value} ")
    }
}

fn indent(depth: usize) -> String {
    "  ".repeat(depth)
}

fn unary_operator(value: JavaUnaryOperator) -> &'static str {
    match value {
        JavaUnaryOperator::Not => "!",
        JavaUnaryOperator::Negate => "-",
        JavaUnaryOperator::BitNot => "~",
    }
}

fn binary_operator(value: JavaBinaryOperator) -> &'static str {
    match value {
        JavaBinaryOperator::LogicalAnd => "&&",
        JavaBinaryOperator::LogicalOr => "||",
        JavaBinaryOperator::Equal => "==",
        JavaBinaryOperator::NotEqual => "!=",
        JavaBinaryOperator::Less => "<",
        JavaBinaryOperator::LessEqual => "<=",
        JavaBinaryOperator::Greater => ">",
        JavaBinaryOperator::GreaterEqual => ">=",
        JavaBinaryOperator::Add => "+",
        JavaBinaryOperator::Subtract => "-",
        JavaBinaryOperator::Multiply => "*",
        JavaBinaryOperator::Divide => "/",
        JavaBinaryOperator::Remainder => "%",
        JavaBinaryOperator::BitAnd => "&",
        JavaBinaryOperator::BitOr => "|",
        JavaBinaryOperator::BitXor => "^",
        JavaBinaryOperator::ShiftLeft => "<<",
        JavaBinaryOperator::ShiftRight => ">>",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn structural_operator_spelling_is_closed() {
        assert_eq!(unary_operator(JavaUnaryOperator::Not), "!");
        assert_eq!(binary_operator(JavaBinaryOperator::ShiftRight), ">>");
    }

    #[test]
    fn switch_patterns_render_complete_case_labels() {
        let names = std::collections::BTreeMap::new();
        assert_eq!(
            render_switch_pattern(&JavaPattern::Literal(JavaLiteral::I32(7)), &names)
                .expect("literal pattern renders"),
            "case 7"
        );
        assert_eq!(
            render_switch_pattern(&JavaPattern::Default, &names).expect("default pattern renders"),
            "default"
        );
    }
}
