use std::collections::BTreeMap;

use portable_check::v0::{Capability, CheckedProgram};
use portable_codegen::{
    Backend, BackendDescriptor, BackendError, BackendOptions, BackendVersion, CapabilitySupport,
    DeclaredDependency, InjectedHelper, IrVersionRange, OptionsSchema, OutputFile, OutputManifest,
    TargetId,
};
use portable_ir::v0::{
    Declaration, ExpectedOutcome, IrVersion, NodeId, TestInvocation, TypeRef, TypedValue, Value,
};

const RUNTIME: &str = include_str!("runtime.go");

pub struct GoV0Backend;

impl Backend for GoV0Backend {
    fn descriptor(&self) -> BackendDescriptor {
        BackendDescriptor {
            target: TargetId::parse("org.polyrust.go").expect("valid target"),
            display_name: "Go".into(),
            backend_version: BackendVersion::new(0, 1, 0),
            supported_ir: IrVersionRange::exact(IrVersion::CURRENT),
        }
    }
    fn support(&self, capability: Capability) -> CapabilitySupport {
        match capability {
            Capability::CheckedIntegerArithmetic => CapabilitySupport::Helper {
                helper: "polyrust.runtime.checked-integers.v0".into(),
            },
            Capability::UnicodeScalar => CapabilitySupport::Helper {
                helper: "polyrust.runtime.unicode-scalars.v0".into(),
            },
            Capability::ImmutableList => CapabilitySupport::Helper {
                helper: "polyrust.runtime.immutable-list.v0".into(),
            },
            Capability::Bytes
            | Capability::ContractDispatch
            | Capability::F64
            | Capability::Option
            | Capability::Result
            | Capability::WrappingIntegerArithmetic
            | Capability::BoundedIteration => CapabilitySupport::Native,
        }
    }
    fn options_schema(&self) -> OptionsSchema {
        BTreeMap::new()
    }
    fn generate(
        &self,
        program: &CheckedProgram,
        _options: &BackendOptions,
    ) -> Result<OutputManifest, BackendError> {
        let generator = Generator::new(program);
        let helpers = program
            .capabilities()
            .program()
            .iter()
            .filter_map(|capability| match self.support(*capability) {
                CapabilitySupport::Helper { helper } => Some(InjectedHelper {
                    id: helper,
                    capability: format!("{capability:?}"),
                    files: vec!["runtime.go".into()],
                }),
                CapabilitySupport::Native | CapabilitySupport::Unsupported { .. } => None,
            })
            .collect();
        OutputManifest::new(
            vec![
                OutputFile::text("go.mod", "module generated.polyrust/package\n\ngo 1.25.0\n"),
                OutputFile::text("runtime.go", RUNTIME),
                OutputFile::text("generated.go", generator.source()?),
                OutputFile::text("generated_test.go", generator.tests()),
                OutputFile::text("conformance_test.go", CONFORMANCE),
            ],
            Vec::<DeclaredDependency>::new(),
            helpers,
        )
        .map_err(BackendError::UnsupportedCapabilities)
    }
}

struct Generator<'a> {
    program: &'a CheckedProgram,
    names: BTreeMap<NodeId, String>,
}

impl<'a> Generator<'a> {
    fn new(program: &'a CheckedProgram) -> Self {
        Self {
            program,
            names: program
                .module()
                .declarations
                .iter()
                .map(|item| (item.header().node.id, item.header().name.clone()))
                .collect(),
        }
    }
    fn source(&self) -> Result<String, BackendError> {
        let document =
            portable_ir::v0::to_canonical_json(self.program.document()).map_err(|error| {
                BackendError::Generation {
                    message: format!("cannot serialize checked IR: {error}"),
                }
            })?;
        let document = String::from_utf8(document).expect("canonical JSON is UTF-8");
        let mut output = format!(
            "// Code generated by PolyRust from checked IR v0. DO NOT EDIT.\npackage generated\n\nvar generatedRuntime = newRuntime({})\n\n",
            go_string(&document)
        );
        let mut declarations: Vec<_> = self.program.module().declarations.iter().collect();
        declarations.sort_by_key(|item| item.header().node.id);
        for declaration in declarations {
            self.declaration(&mut output, declaration);
        }
        Ok(output)
    }
    fn declaration(&self, output: &mut String, declaration: &Declaration) {
        match declaration {
            Declaration::Alias(item) => output.push_str(&format!("type {} = {}\n\n", exported(&item.header.name), self.ty(&item.target))),
            Declaration::Record(item) => {
                output.push_str(&format!("type {} struct {{\n", exported(&item.header.name))); for member in &item.fields { output.push_str(&format!("\t{} {}\n", exported(&member.header.name), self.ty(&member.ty))); } output.push_str("}\n\n");
                output.push_str(&format!("func (value {}) polyValue() map[string]any {{ return map[string]any{{\"__polyDecl\": int64({})", exported(&item.header.name), item.header.node.id.0)); for member in &item.fields { output.push_str(&format!(", {:?}: value.{}", member.header.name, exported(&member.header.name))); } output.push_str("} }\n\n");
                for implementation in self.implementations(item.header.node.id) { output.push_str(&format!("var _ {} = {}{{}}\n\n", exported(self.name(implementation.contract)), exported(&item.header.name))); for method in &implementation.methods { output.push_str(&format!("func (value {}) {}({}) PolyResult[{}] {{ return castResult[{}](generatedRuntime.invokeMethod({}, {}, value, []any{{{}}})) }}\n\n", exported(&item.header.name), exported(&method.header.name), self.parameters(&method.parameters), self.ty(&method.return_type), self.ty(&method.return_type), implementation.header.node.id.0, method.header.node.id.0, args(&method.parameters))); } }
            }
            Declaration::Enum(item) => { let mut variants = Vec::new(); for variant in &item.variants { let name = format!("{}{}", exported(&item.header.name), exported(&variant.header.name)); variants.push(name.clone()); output.push_str(&format!("type {name} struct {{\n\tTag string\n")); for member in &variant.fields { output.push_str(&format!("\t{} {}\n", exported(&member.header.name), self.ty(&member.ty))); } output.push_str("}\n\n"); } output.push_str(&format!("type {} interface {{ is{}() }}\n", exported(&item.header.name), exported(&item.header.name))); for variant in variants { output.push_str(&format!("func ({variant}) is{}() {{}}\n", exported(&item.header.name))); } output.push('\n'); }
            Declaration::Contract(item) => { output.push_str(&format!("type {} interface {{\n\tpolyValue() map[string]any\n", exported(&item.header.name))); for method in &item.methods { output.push_str(&format!("\t{}({}) PolyResult[{}]\n", exported(&method.header.name), self.parameters(&method.parameters), self.ty(&method.return_type))); } output.push_str("}\n\n"); }
            Declaration::Constant(item) => output.push_str(&format!("func {}() PolyResult[{}] {{ return castResult[{}](generatedRuntime.constant({})) }}\n\n", exported(&item.header.name), self.ty(&item.ty), self.ty(&item.ty), item.header.node.id.0)),
            Declaration::Function(item) => output.push_str(&format!("func {}({}) PolyResult[{}] {{ return castResult[{}](generatedRuntime.invoke({}, []any{{{}}})) }}\n\n", exported(&item.header.name), self.parameters(&item.parameters), self.ty(&item.return_type), self.ty(&item.return_type), item.header.node.id.0, args(&item.parameters))),
            Declaration::Implementation(_) | Declaration::Test(_) => {}
        }
    }
    fn implementations(&self, record: NodeId) -> Vec<&portable_ir::v0::ImplementationDeclaration> {
        self.program
            .module()
            .declarations
            .iter()
            .filter_map(|item| match item {
                Declaration::Implementation(value) if value.record == record => Some(value),
                _ => None,
            })
            .collect()
    }
    fn parameters(&self, parameters: &[portable_ir::v0::Parameter]) -> String {
        parameters
            .iter()
            .map(|item| format!("{} {}", local(&item.header.name), self.ty(&item.ty)))
            .collect::<Vec<_>>()
            .join(", ")
    }
    fn ty(&self, ty: &TypeRef) -> String {
        match ty {
            TypeRef::Unit => "struct{}".into(),
            TypeRef::Bool => "bool".into(),
            TypeRef::I32 => "int32".into(),
            TypeRef::I64 => "int64".into(),
            TypeRef::F64 => "float64".into(),
            TypeRef::Char => "rune".into(),
            TypeRef::String => "string".into(),
            TypeRef::Bytes => "PolyBytes".into(),
            TypeRef::List(inner) => format!("PolyList[{}]", self.ty(inner)),
            TypeRef::Option(inner) => format!("PolyOption[{}]", self.ty(inner)),
            TypeRef::Result { ok, error } => {
                format!("PolyValueResult[{}, {}]", self.ty(ok), self.ty(error))
            }
            TypeRef::Named(id) | TypeRef::Contract(id) => exported(self.name(*id)),
        }
    }
    fn name(&self, id: NodeId) -> &str {
        self.names.get(&id).map(String::as_str).unwrap_or("Unknown")
    }
    fn tests(&self) -> String {
        let mut output = String::from(
            "// Code generated from portable tests. DO NOT EDIT.\npackage generated\n\nimport \"testing\"\n\n",
        );
        for declaration in &self.program.module().declarations {
            if let Declaration::Test(test) = declaration {
                output.push_str(&format!(
                    "func Test{}(t *testing.T) {{\n",
                    exported(&test.header.name)
                ));
                let call = match &test.invocation {
                    TestInvocation::Function {
                        function,
                        arguments,
                    } => format!(
                        "{}({})",
                        exported(self.name(*function)),
                        arguments
                            .iter()
                            .map(|value| self.value(value))
                            .collect::<Vec<_>>()
                            .join(", ")
                    ),
                    TestInvocation::Method {
                        implementation,
                        method,
                        receiver,
                        arguments,
                    } => format!(
                        "{}.{}({})",
                        self.value(receiver),
                        exported(self.method_name(*implementation, *method)),
                        arguments
                            .iter()
                            .map(|value| self.value(value))
                            .collect::<Vec<_>>()
                            .join(", ")
                    ),
                };
                match &test.expected { ExpectedOutcome::Value(expected) => output.push_str(&format!("\tgot := {call}\n\tif !got.Ok || !equal(got.Value, {}) {{ t.Fatalf(\"unexpected result: %#v\", got) }}\n", self.value(expected))), ExpectedOutcome::Error(_) => output.push_str(&format!("\tgot := {call}\n\tif got.Ok {{ t.Fatalf(\"expected error: %#v\", got) }}\n")) }
                output.push_str("}\n\n");
            }
        }
        output
    }
    fn method_name(&self, implementation: NodeId, method: NodeId) -> &str {
        self.program
            .module()
            .declarations
            .iter()
            .find_map(|item| match item {
                Declaration::Implementation(value) if value.header.node.id == implementation => {
                    value
                        .methods
                        .iter()
                        .find(|item| {
                            item.header.node.id == method || item.contract_method == method
                        })
                        .map(|item| item.header.name.as_str())
                }
                _ => None,
            })
            .unwrap_or("Unknown")
    }
    fn value(&self, typed: &TypedValue) -> String {
        self.raw_value(&typed.value, &typed.ty)
    }
    fn raw_value(&self, value: &Value, ty: &TypeRef) -> String {
        match (value, ty) {
            (Value::Unit, _) => "struct{}{}".into(),
            (Value::Bool(value), _) => value.to_string(),
            (Value::I32(value), _) => format!("int32({value})"),
            (Value::I64(value), _) => format!("int64({value})"),
            (Value::String(value), _) => go_string(value),
            (
                Value::Record {
                    declaration,
                    fields,
                },
                _,
            ) => {
                let Declaration::Record(record) = self
                    .program
                    .module()
                    .declarations
                    .iter()
                    .find(|item| item.header().node.id == *declaration)
                    .expect("checked record")
                else {
                    unreachable!()
                };
                format!(
                    "{}{{{}}}",
                    exported(&record.header.name),
                    fields
                        .iter()
                        .map(|field| {
                            let member = record
                                .fields
                                .iter()
                                .find(|item| item.header.node.id == field.field)
                                .expect("checked field");
                            format!(
                                "{}: {}",
                                exported(&member.header.name),
                                self.raw_value(&field.value, &member.ty)
                            )
                        })
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            }
            _ => "nil".into(),
        }
    }
}

fn args(parameters: &[portable_ir::v0::Parameter]) -> String {
    parameters
        .iter()
        .map(|item| local(&item.header.name))
        .collect::<Vec<_>>()
        .join(", ")
}
fn exported(name: &str) -> String {
    let mut result = String::new();
    for word in name
        .split(|value: char| !value.is_ascii_alphanumeric())
        .filter(|word| !word.is_empty())
    {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            result.extend(chars);
        }
    }
    if result.is_empty() {
        "Generated".into()
    } else {
        result
    }
}
fn local(name: &str) -> String {
    let value = exported(name);
    let mut chars = value.chars();
    let first = chars.next().unwrap_or('v').to_ascii_lowercase();
    format!("{first}{}", chars.collect::<String>())
}
fn go_string(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            character if character.is_control() => {
                output.push_str(&format!("\\u{:04x}", character as u32));
            }
            character => output.push(character),
        }
    }
    output.push('"');
    output
}

const CONFORMANCE: &str = "package generated\n\nimport (\n \"math\"\n \"testing\"\n)\n\nfunc TestTwentySemanticVectors(t *testing.T) {\n source := NewPolyList(int32(1)); appended := source.append(2)\n wide32 := uint32(2147483648); wide64 := uint64(9223372036854775808)\n vectors := []bool{\n  checked32(0).Ok, checked32(2147483647).Ok, checked32(-2147483648).Ok, !checked32(2147483648).Ok, !checked32(-2147483649).Ok,\n  int64(0) == 0, int64(9223372036854775807) > 0, int64(-9223372036854775807-1) < 0,\n  int32(wide32) == -2147483648, int64(wide64) == -9223372036854775807-1,\n  len([]rune(\"a\")) == 1, len([]rune(\"😀\")) == 1, NewPolyBytes(1,2).Values()[1] == 2,\n  source.Len() == 1, appended.Len() == 2, len(source.Values()) == 1, len(appended.Values()) == 2,\n  PolyOption[int]{Tag:\"none\"}.Tag == \"none\", PolyOption[int]{Tag:\"some\",Value:0}.Tag == \"some\", math.Signbit(math.Copysign(0,-1)),\n }\n if len(vectors)!=20 { t.Fatal(len(vectors)) }; for index,value:=range vectors { if !value { t.Fatal(index) } }\n}\n";

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn deterministic_and_i64() {
        let checked = fixture();
        let first = GoV0Backend
            .generate(&checked, &BackendOptions::default())
            .unwrap();
        let second = GoV0Backend
            .generate(&checked, &BackendOptions::default())
            .unwrap();
        assert_eq!(first.canonical_json(), second.canonical_json());
        assert_eq!(Generator::new(&checked).ty(&TypeRef::I64), "int64");
    }
    #[test]
    fn strings_use_only_valid_go_escapes_and_preserve_unicode() {
        assert_eq!(
            go_string("\0\u{8}\n\r\t\\\"\u{301}🦄"),
            "\"\\u0000\\u0008\\n\\r\\t\\\\\\\"\u{301}🦄\""
        );
    }
    fn fixture() -> CheckedProgram {
        portable_check::v0::check_program(
            portable_ir::v0::from_json(include_bytes!(
                "../../build/testdata/registration.poly.json"
            ))
            .unwrap(),
        )
        .unwrap()
    }
}
