//! Strict ESM TypeScript generation from checked portable IR v0.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;

use portable_check::v0::{Capability, CheckedProgram};
use portable_codegen::{
    Backend, BackendDescriptor, BackendError, BackendOptions, BackendVersion, CapabilitySupport,
    DeclaredDependency, InjectedHelper, IrVersionRange, OptionsSchema, OutputFile, OutputManifest,
    TargetId,
};
use portable_ir::v0::{Declaration, IrVersion, NodeId, TypeRef, Visibility};

const RUNTIME: &str = include_str!("runtime.ts");

pub struct TypeScriptBackend;

impl Backend for TypeScriptBackend {
    fn descriptor(&self) -> BackendDescriptor {
        BackendDescriptor {
            target: TargetId::parse("org.polyrust.typescript").expect("static target ID is valid"),
            display_name: "TypeScript".to_owned(),
            backend_version: BackendVersion::new(0, 1, 0),
            supported_ir: IrVersionRange::exact(IrVersion::CURRENT),
        }
    }

    fn support(&self, capability: Capability) -> CapabilitySupport {
        match capability {
            Capability::CheckedIntegerArithmetic => CapabilitySupport::Helper {
                helper: "polyrust.runtime.checked-integers.v0".into(),
            },
            Capability::UnicodeScalar => CapabilitySupport::Helper {
                helper: "polyrust.runtime.unicode-scalars.v0".into(),
            },
            Capability::ImmutableList => CapabilitySupport::Helper {
                helper: "polyrust.runtime.immutable-list.v0".into(),
            },
            Capability::Bytes
            | Capability::ContractDispatch
            | Capability::F64
            | Capability::Option
            | Capability::Result
            | Capability::WrappingIntegerArithmetic
            | Capability::BoundedIteration => CapabilitySupport::Native,
        }
    }

    fn options_schema(&self) -> OptionsSchema {
        BTreeMap::new()
    }

    fn generate(
        &self,
        program: &CheckedProgram,
        _options: &BackendOptions,
    ) -> Result<OutputManifest, BackendError> {
        let generator = Generator::new(program);
        let helpers = program
            .capabilities()
            .program()
            .iter()
            .filter_map(|capability| match self.support(*capability) {
                CapabilitySupport::Helper { helper } => Some(InjectedHelper {
                    id: helper,
                    capability: format!("{capability:?}"),
                    files: vec!["src/runtime.ts".into()],
                }),
                CapabilitySupport::Native | CapabilitySupport::Unsupported { .. } => None,
            })
            .collect();
        OutputManifest::new(
            vec![
                OutputFile::text("package.json", PACKAGE_JSON),
                OutputFile::text("tsconfig.json", TSCONFIG),
                OutputFile::text("src/runtime.ts", RUNTIME),
                OutputFile::text("src/index.ts", generator.index()?),
                OutputFile::text("src/generated.test.ts", generator.tests()),
                OutputFile::text("src/conformance.test.ts", CONFORMANCE),
                OutputFile::text("src/node-shims.d.ts", NODE_SHIMS),
                OutputFile::text("tests/invalid-types.ts", INVALID_TYPES),
            ],
            Vec::<DeclaredDependency>::new(),
            helpers,
        )
        .map_err(BackendError::UnsupportedCapabilities)
    }
}

struct Generator<'a> {
    program: &'a CheckedProgram,
    names: BTreeMap<NodeId, String>,
}

impl<'a> Generator<'a> {
    fn new(program: &'a CheckedProgram) -> Self {
        let names = program
            .module()
            .declarations
            .iter()
            .map(|declaration| {
                (
                    declaration.header().node.id,
                    declaration.header().name.clone(),
                )
            })
            .collect();
        Self { program, names }
    }

    fn index(&self) -> Result<String, BackendError> {
        let mut document = serde_json::to_value(self.program.document()).map_err(|error| {
            BackendError::Generation {
                message: format!("cannot serialize checked IR: {error}"),
            }
        })?;
        stringify_wide_numbers(&mut document);
        let document = serde_json::to_string(&document).expect("checked document serializes");
        let mut output = String::from(
            "// Generated by PolyRust from checked IR v0.\nimport { Runtime, type PolyResult } from \"./runtime.js\";\nexport * from \"./runtime.js\";\n\n",
        );
        output.push_str("const runtime = new Runtime(");
        output.push_str(&document);
        output.push_str(");\nconst castResult = <T>(value: PolyResult<unknown>): PolyResult<T> => value as PolyResult<T>;\n\n");
        let mut declarations: Vec<_> = self.program.module().declarations.iter().collect();
        declarations.sort_by_key(|declaration| declaration.header().node.id);
        for declaration in declarations {
            self.declaration(&mut output, declaration);
        }
        output.push_str("export const __invokeTest = (index: number): Readonly<{ actual: PolyResult<unknown>; expected: unknown; expectsError: boolean }> => {\n  const test = TESTS[index];\n  if (test === undefined) return { actual: { ok: false, error: { code: \"invalid_test\", message: \"unknown test\" } }, expected: undefined, expectsError: true };\n  const invocation = test.invocation;\n  const arguments_ = invocation.data.arguments.map((value: unknown) => runtime.decode(value));\n  const actual = invocation.kind === \"function\" ? runtime.invoke(invocation.data.function, arguments_) : runtime.invokeMethod(invocation.data.implementation, invocation.data.method, runtime.decode(invocation.data.receiver), arguments_);\n  return { actual, expected: runtime.decode(test.expected.data), expectsError: test.expected.kind === \"error\" };\n};\n");
        let tests: Vec<_> = self.program.module().declarations.iter().filter_map(|declaration| if let Declaration::Test(test) = declaration { Some(serde_json::json!({"invocation": test.invocation, "expected": test.expected})) } else { None }).collect();
        output.push_str("const TESTS: readonly any[] = ");
        output.push_str(&serde_json::to_string(&tests).expect("tests serialize"));
        output.push_str(";\n");
        Ok(output)
    }

    fn declaration(&self, output: &mut String, declaration: &Declaration) {
        match declaration {
            Declaration::Alias(item) => output.push_str(&format!(
                "{}type {} = {};\n\n",
                export(item.header.visibility),
                type_name(&item.header.name),
                self.ty(&item.target)
            )),
            Declaration::Record(item) => {
                let implementations: Vec<_> = self
                    .program
                    .module()
                    .declarations
                    .iter()
                    .filter_map(|candidate| match candidate {
                        Declaration::Implementation(value)
                            if value.record == item.header.node.id =>
                        {
                            Some(value)
                        }
                        _ => None,
                    })
                    .collect();
                let contracts = implementations
                    .iter()
                    .map(|implementation| type_name(self.name(implementation.contract)))
                    .collect::<Vec<_>>()
                    .join(", ");
                output.push_str(&format!(
                    "{}class {}{} {{\n  public readonly __polyDecl = {};\n",
                    export(item.header.visibility),
                    type_name(&item.header.name),
                    if contracts.is_empty() {
                        String::new()
                    } else {
                        format!(" implements {contracts}")
                    },
                    item.header.node.id.0
                ));
                for field in &item.fields {
                    output.push_str(&format!(
                        "  public readonly {}: {};\n",
                        value_name(&field.header.name),
                        self.ty(&field.ty)
                    ));
                }
                output.push_str(&format!(
                    "  public constructor({}) {{\n",
                    item.fields
                        .iter()
                        .map(|field| format!(
                            "{}: {}",
                            value_name(&field.header.name),
                            self.ty(&field.ty)
                        ))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
                for field in &item.fields {
                    output.push_str(&format!(
                        "    this.{} = {};\n",
                        value_name(&field.header.name),
                        value_name(&field.header.name)
                    ));
                }
                output.push_str("    Object.freeze(this);\n  }\n");
                for implementation in implementations {
                    for method in &implementation.methods {
                        output.push_str(&format!("  public {}({}): PolyResult<{}> {{ return castResult(runtime.invokeMethod({}, {}, this, [{}])); }}\n", value_name(&method.header.name), self.parameters(&method.parameters), self.ty(&method.return_type), implementation.header.node.id.0, method.header.node.id.0, method.parameters.iter().map(|parameter| value_name(&parameter.header.name)).collect::<Vec<_>>().join(", ")));
                    }
                }
                output.push_str("}\n\n");
            }
            Declaration::Enum(item) => {
                let variants = item
                    .variants
                    .iter()
                    .map(|variant| {
                        let mut fields = vec![format!("readonly tag: {:?}", variant.header.name)];
                        fields.extend(variant.fields.iter().map(|field| {
                            format!(
                                "readonly {}: {}",
                                value_name(&field.header.name),
                                self.ty(&field.ty)
                            )
                        }));
                        format!("Readonly<{{ {} }}>", fields.join("; "))
                    })
                    .collect::<Vec<_>>()
                    .join(" | ");
                output.push_str(&format!(
                    "{}type {} = {};\n\n",
                    export(item.header.visibility),
                    type_name(&item.header.name),
                    variants
                ));
            }
            Declaration::Contract(item) => {
                output.push_str(&format!(
                    "{}interface {} {{\n",
                    export(item.header.visibility),
                    type_name(&item.header.name)
                ));
                for method in &item.methods {
                    output.push_str(&format!(
                        "  {}({}): PolyResult<{}>;\n",
                        value_name(&method.header.name),
                        self.parameters(&method.parameters),
                        self.ty(&method.return_type)
                    ));
                }
                output.push_str("}\n\n");
            }
            Declaration::Constant(item) => output.push_str(&format!(
                "{}const {} = (): PolyResult<{}> => castResult(runtime.readConstant({}));\n\n",
                export(item.header.visibility),
                value_name(&item.header.name),
                self.ty(&item.ty),
                item.header.node.id.0
            )),
            Declaration::Function(item) => output.push_str(&format!(
                "{}const {} = ({}): PolyResult<{}> => castResult(runtime.invoke({}, [{}]));\n\n",
                export(item.header.visibility),
                value_name(&item.header.name),
                self.parameters(&item.parameters),
                self.ty(&item.return_type),
                item.header.node.id.0,
                item.parameters
                    .iter()
                    .map(|parameter| value_name(&parameter.header.name))
                    .collect::<Vec<_>>()
                    .join(", ")
            )),
            Declaration::Implementation(_) | Declaration::Test(_) => {}
        }
    }

    fn parameters(&self, parameters: &[portable_ir::v0::Parameter]) -> String {
        parameters
            .iter()
            .map(|parameter| {
                format!(
                    "{}: {}",
                    value_name(&parameter.header.name),
                    self.ty(&parameter.ty)
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn ty(&self, ty: &TypeRef) -> String {
        match ty {
            TypeRef::Unit => "undefined".into(),
            TypeRef::Bool => "boolean".into(),
            TypeRef::I32 | TypeRef::F64 => "number".into(),
            TypeRef::I64 => "bigint".into(),
            TypeRef::Char | TypeRef::String => "string".into(),
            TypeRef::Bytes => "readonly number[]".into(),
            TypeRef::List(inner) => format!("readonly {}[]", parenthesize(self.ty(inner))),
            TypeRef::Option(inner) => {
                format!("import(\"./runtime.js\").PolyOption<{}>", self.ty(inner))
            }
            TypeRef::Result { ok, error } => format!(
                "import(\"./runtime.js\").PolyValueResult<{}, {}>",
                self.ty(ok),
                self.ty(error)
            ),
            TypeRef::Named(id) | TypeRef::Contract(id) => type_name(self.name(*id)),
        }
    }

    fn name(&self, id: NodeId) -> &str {
        self.names.get(&id).map(String::as_str).unwrap_or("Unknown")
    }

    fn tests(&self) -> String {
        let mut output = String::from(
            "import assert from \"node:assert/strict\";\nimport test from \"node:test\";\nimport { __invokeTest } from \"./index.js\";\n\n",
        );
        let mut index = 0;
        for declaration in &self.program.module().declarations {
            if let Declaration::Test(test_declaration) = declaration {
                output.push_str(&format!("test({:?}, () => {{ const result = __invokeTest({index}); assert.equal(result.actual.ok, !result.expectsError); if (result.actual.ok) assert.deepEqual(result.actual.value, result.expected); }});\n", test_declaration.header.name));
                index += 1;
            }
        }
        output
    }
}

fn export(visibility: Visibility) -> &'static str {
    if visibility == Visibility::Public {
        "export "
    } else {
        ""
    }
}
fn type_name(name: &str) -> String {
    identifier(name)
}
fn value_name(name: &str) -> String {
    identifier(name)
}
fn parenthesize(ty: String) -> String {
    if ty.contains(" | ") {
        format!("({ty})")
    } else {
        ty
    }
}
fn identifier(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "debugger",
        "default",
        "delete",
        "do",
        "else",
        "enum",
        "export",
        "extends",
        "false",
        "finally",
        "for",
        "function",
        "if",
        "import",
        "in",
        "instanceof",
        "new",
        "null",
        "return",
        "super",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "var",
        "void",
        "while",
        "with",
        "yield",
        "interface",
        "implements",
        "package",
        "private",
        "protected",
        "public",
        "static",
        "await",
    ];
    if KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_owned()
    }
}

fn stringify_wide_numbers(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Array(values) => {
            for value in values {
                stringify_wide_numbers(value);
            }
        }
        serde_json::Value::Object(object) => {
            if matches!(
                object.get("kind").and_then(serde_json::Value::as_str),
                Some("i64" | "f64")
            ) && let Some(data) = object.get_mut("data")
                && data.is_number()
            {
                *data = serde_json::Value::String(data.to_string());
            }
            for value in object.values_mut() {
                stringify_wide_numbers(value);
            }
        }
        _ => {}
    }
}

const PACKAGE_JSON: &str = "{\n  \"name\": \"generated-polyrust-package\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": {\n    \"typecheck\": \"tsc --noEmit\",\n    \"test\": \"tsc && node --test dist/*.test.js\"\n  }\n}\n";
const TSCONFIG: &str = "{\n  \"compilerOptions\": {\n    \"target\": \"ES2024\",\n    \"module\": \"NodeNext\",\n    \"moduleResolution\": \"NodeNext\",\n    \"strict\": true,\n    \"noImplicitAny\": true,\n    \"noUncheckedIndexedAccess\": true,\n    \"exactOptionalPropertyTypes\": true,\n    \"rootDir\": \"src\",\n    \"outDir\": \"dist\",\n    \"declaration\": true,\n    \"skipLibCheck\": true\n  },\n  \"include\": [\"src/**/*.ts\"],\n  \"exclude\": [\"tests\"]\n}\n";
const CONFORMANCE: &str = "import assert from \"node:assert/strict\";\nimport test from \"node:test\";\nimport { checkedI32, checkedI64, listAppend, scalarLength, wrappingI32, wrappingI64 } from \"./runtime.js\";\n\ntest(\"20 semantic boundary vectors\", () => {\n  const astral = scalarLength(\"😀\");\n  const original: readonly number[] = [1];\n  const appended = listAppend(original, 2);\n  const vectors: readonly boolean[] = [\n    checkedI32(0).ok, checkedI32(2147483647).ok, checkedI32(-2147483648).ok, !checkedI32(2147483648).ok, !checkedI32(-2147483649).ok,\n    checkedI64(0n).ok, checkedI64(9223372036854775807n).ok, checkedI64(-9223372036854775808n).ok, !checkedI64(9223372036854775808n).ok, !checkedI64(-9223372036854775809n).ok,\n    wrappingI32(2147483648) === -2147483648, wrappingI32(-2147483649) === 2147483647, wrappingI64(9223372036854775808n) === -9223372036854775808n, wrappingI64(-9223372036854775809n) === 9223372036854775807n,\n    scalarLength(\"a\").ok, astral.ok && astral.value === 1, !scalarLength(\"\\ud800\").ok, appended.length === 2, appended !== original, Object.is(-0, -0),\n  ];\n  assert.equal(vectors.length, 20); assert.ok(vectors.every(Boolean));\n});\n";
const INVALID_TYPES: &str = "import type { PolyOption } from \"../src/runtime.js\";\n// @ts-expect-error invalid option tag must be rejected\nconst invalid: PolyOption<number> = { tag: \"missing\" };\nvoid invalid;\n";
const NODE_SHIMS: &str = "declare module \"node:assert/strict\" { const assert: { equal(actual: unknown, expected: unknown): void; deepEqual(actual: unknown, expected: unknown): void; ok(value: unknown): void }; export default assert; }\ndeclare module \"node:test\" { const test: (name: string, body: () => void) => void; export default test; }\n";

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn keywords_are_escaped_and_i64_is_bigint() {
        assert_eq!(identifier("class"), "class_");
        assert_eq!(Generator::new(&fixture()).ty(&TypeRef::I64), "bigint");
    }
    #[test]
    fn generated_manifest_is_deterministic_and_strict() {
        let checked = fixture();
        let first = TypeScriptBackend
            .generate(&checked, &BackendOptions::default())
            .unwrap();
        let second = TypeScriptBackend
            .generate(&checked, &BackendOptions::default())
            .unwrap();
        assert_eq!(first.canonical_json(), second.canonical_json());
        let index = first
            .files()
            .iter()
            .find(|file| file.path() == "src/index.ts")
            .unwrap();
        let portable_codegen::OutputContents::Text(index) = index.contents() else {
            panic!("text")
        };
        assert!(index.contains("bigint") || index.contains("call_render"));
        assert!(TSCONFIG.contains("\"strict\": true"));
    }
    fn fixture() -> CheckedProgram {
        let document = portable_ir::v0::from_json(include_bytes!(
            "../../build/testdata/registration.poly.json"
        ))
        .unwrap();
        portable_check::v0::check_program(document).unwrap()
    }
}
